### ISSUE TITLE
Artefacts in saturated areas

### ISSUE THREAD

**Issue by howff** [ssec/polar2grid#146]
When I reproject a VIIRS i-band using viirs_sdr gtiff I get artefacts in saturated areas.
In this case the white areas are turning black.
When I queried something similar in output from IPOPP the response was that the quality flags were indicating a saturated value and that impacted the output. In some cases a software patch was able to resolve it but in other cases it was sadly "working as designed" (i.e. won't fix). I don't know if it's the same cause in polar2grid or something else.
![npp_viirs_i02_20180208_150127_mapping6_500_crop-crop](https://user-images.githubusercontent.com/3064316/36025852-84815800-0d8c-11e8-9f7b-8e138733c21f.jpg)

**Comment by davidh-ssec** [comment]
I don't remember there being a saturated flag value for VIIRS. Any chance you could provide some data files?

**Comment by howff** [comment]
https://wetransfer.com/downloads/6147f06c69b975332bf83aadcab5231d20180209115539/83230738f740d06df761273f607fd47020180209115539/122e5a
https://wetransfer.com/downloads/3336ffd255accde0ffb90b4a076e653920180209115848/ce4ec116a1cf636d0372b8bc9515b4e820180209115848/31629a
https://wetransfer.com/downloads/3dab25e084085b97a3af6122c065e6a620180209120121/1fcd6f943ed537945bcb119951ada4b320180209120121/42a4c3

**Comment by davidh-ssec** [comment]
@howff After talking with @kathys, she reminded me that we have had users ask about this issue before. In the past it has been an issue with the M07 band when it is reconstructed from the I02 band. In I02 the fill value is 65528 (SOUB - scaled out-of-bounds / solution not within allowed range) and when M07 is reconstructed this becomes 65531 which is definitely a fill value that has to be masked out. We could include the 65528 values in P2G, but the description of the fill value makes me a little worried that it might have negative effects somewhere else in the processing. By that I mean, is 65528 always used for saturated pixels or is it sometimes used for extremely dark pixels or is it ever used for calculations that results in bad values (solution not within allowed range). If so we can't confidently convert 65528 to maximum reflectance values. Do you have any more knowledge on these fill values? Does this make sense?

**Comment by howff** [comment]
I guess it would have been helpful if there were two SOUB values, one for each bound that has been exceeded. I'm assuming a reflectance of zero is unlikely but possible, but is a negative reflectance a possible result from the algorithm? If so then we don't know whether to replace it with 0 or 1. But if a negative result is impossible then replacing it with 1 is ok.

**Comment by davidh-ssec** [comment]
The previous issue you created with the bright cyan/green-ish pixels was due to negative reflectances and reflectances near zero.

**Comment by djhoese** [comment]
@kathys Coming back to this issue after 4 years, I think the end result is that this is something out of our control. The saturated pixels are being marked by the SDR processing as invalid when M07 is reconstructed and there isn't enough information for Polar2Grid (or rather Satpy nowadays) to know how to replace the pixel to make a pretty picture. Unless someone comes up with something else, I think I'll close this in a couple days.

**Comment by kathys** [comment]
Okay.  Sounds reasonable @djhoese.
