### ISSUE TITLE
How to adjust the thickness of coastline?

### ISSUE THREAD

**Issue by songhan89** [ssec/polar2grid#149]
Hi David,

I wish to check if there is any way of adjusting the thickness of coastline with the latest polar2grid?

**Comment by songhan89** [comment]
Thanks David!

Would be a bonus if we can overlay the active fires using p2g too!

**Comment by djhoese** [comment]
@songhan89 If you are comfortable with python it may be worth looking at the satpy (http://satpy.readthedocs.io/en/latest/) project and pycoast library which back polar2grid.

**Comment by djhoese** [comment]
This should be available in the next Polar2Grid release. Thanks for the suggestion.
