### ISSUE TITLE
VIIRS EDR Active Fires composite

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#170]
In the next version of P2G we will have a viirs edr active fires reader. To get the most out of this we will need to provide a way of compositing the resulting fires image with another image (ex. true color).

We could use the `gdal_merge.py` utility as a secondary step to combine two geotiffs where the first one is the background, the second one is the foreground/fires. We will need to investigate how gdal_merge.py uses L+colortable images on top of RGB images. Could add a `gdal_translate` call before `gdal_merge.py` to convert the L+colortable to RGB/A.

`</braindump>`

**Comment by songhan89** [comment]
Hi David,

This is a good idea. I had to make a separate plotting script using matplotlib to achieve this. I have a hotspot counting module using geopandas as well. Not sure if you think would be good to integrate this.

http://asmc.asean.org/satellite-polar/ (We are producing true colour, dynamic DNB and false colour)

![HighResTrueColor_N20_Sumatra_20190627_000000](https://user-images.githubusercontent.com/15259500/60274808-56c67180-992b-11e9-9aec-0cba11147a01.jpg)

**Comment by djhoese** [comment]
I just realized this issue exists. I made https://github.com/ssec/polar2grid/issues/183 which is essentially a duplicate of this. I'll post some screenshots of the "raw" composite I generated there.

**Comment by djhoese** [comment]
There will now be an `overlay.sh` script to help with this type of operation (put one image on top of another) in the 2.3 release of Polar2Grid. Closing this now in anticipation of the next release. If there are other concerns or issues then a new issue can be made.
