### ISSUE TITLE
polar2grid v2.3a1 task list

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#197]
- [x]  Active Fire GeoTIFF creation fails when trying to create AFMOD*.nc confidence_pct product.  Test machine was dragon (CenOS6).  
Test data and log files available at bumi:/data/users/kathys/test_data/active_fire
Log files and screen output in bumi:/data/users/kathys/test_data/active_fire/run

- [x] Default --grid-coverage percent should be 0 for the active fire geotiff file writer because the coverage of this product will (hopefully) always be small, unless the apocalypse is occurring.

**Comment by djhoese** [comment]
These are all fixed now.
