### ISSUE TITLE
No default products for viirs_edr_active_fires reader in polar2grid 2.3.0a2 

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#203]
Using tarball polar2grid-swbundle-2.3.0a2.tar.gz, there are apparently no defaults for the new viirs_edr_active_fires reader.  If you execute the software in this manner:

polar2grid.sh viirs_edr_active_fires gtiff -f ../fire_img/*.nc

it fails.  However, the good news is that it creates products when providing products to the reader via the -p option, such as:

polar2grid.sh viirs_edr_active_fires gtiff -p T13 confidence_pct power -f ../fire_mod

You can use the same test data as provided previously at bumi:/data/users/kathys/test_data/active_fire

The defaults should be:

IMG resolution files:   T4  confidence_dat   power

MOD resolution files:  T13  confidence_pct  power

**Comment by djhoese** [comment]
We'll see what happens, but I may have to code it as all of them being defaults, but Satpy/P2G will figure out that it can't load the ones that it can't load.
