### ISSUE TITLE
mersi2 reader issues in polar2grid-swbundle-2.3.0a2

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#207]
- [ ]  mersi2_l1b reader does not have any defined product defaults.  Should follow MODIS/VIIRS pattern which is to create images of all bands that are possible based upon the input data.

- [ ] Although --list-products provides the option of 25 bands, band 24 and 25 are not successfully created.  This nighttime test data is available at:

/data/users/kathys/test_data/fy3d_mersi/night/l1b

and log file with gtiff output files are at:

bumi:/data/users/kathys/test_data/fy3d_mersi/night/gtiff

- [ ]  Reflectance band images should not be created for nighttime data sets like this one.  For  VIIRS/MODIS there is a day/night threshold that is used.  When I processed this data, it created images for all bands, even though all but 6 of the bands are reflected solar bands.  It would be optimal if creation of these bands would work in  a similar way as the other imagers.

**Comment by kathys** [comment]
Update:  Trying to create nighttime images using the data referenced above with polar2grid-swbundle-2.3.0b0.tar.gz.  The software fails with a strange error message:

From bumi:/data/users/kathys/test_data/fy3d_mersi/night/gtiff
Command:  polar2grid.sh mersi2_l1b gtiff -g lcc_fit -f ../l1b/tf2019226095418.FY3D-X_MERSI_*.HDF

..ERROR    : Binary file already exists: 7.dat
ERROR    : Frontend data extraction failed (see log for details)

Log file is in the execution directory

**Comment by djhoese** [comment]
Can you double check that the execution directory is completely empty when you start processing?
