### ISSUE TITLE
polar2grid-swbundle-2.3.0a2 - flood reader fails to produce GeoTIFF

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#211]
Testing out the new VIIRS Flood Product Reader, and it does work to list out products from a valid HDF file, but it fails to produce any output, no matter what writer I choose.

**Exections:**  
polar2grid.sh viirs_edr_flood gtiff --list-products  -f ../tmp/WATER_VIIRS_Prj_SVI_npp_d20180226_t1926505_e1929401_b32823_cspp_dev_10593_4348_01.hdf 
INFO     : Initializing reader...
WaterDetection

polar2grid.sh viirs_edr_flood gtiff -p WaterDetection -f ../tmp/WATER_VIIRS_Prj_SVI_npp_d20180226_t1926505_e1929401_b32823_cspp_dev_10593_4348_01.hdf 
INFO     : Initializing reader...
INFO     : Initializing remapping...
INFO     : Initializing backend...
INFO     : Initializing compositor objects...
INFO     : Extracting swaths from data files available...
ERROR    : Unexpected error. Enable debug messages (-vvv) or see log file for details.

The test data is at bumi:/data/users/kathys/test_data/flood

Log file is here:  bumi:/data/users/kathys/test_data/flood/log
and I also attached the logfile to this entry.

[viirs_edr_flood2gtiff_20180226_192650.log](https://github.com/ssec/polar2grid/files/3536159/viirs_edr_flood2gtiff_20180226_192650.log)

**Comment by djhoese** [comment]
This turned out to be a bug in how satpy was passing HDF4 data to dask/numpy. This should be fixed in current Satpy master and available in the 2.3.0a3 tarball.
