### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by KNLargadas** [ssec/polar2grid#225]
I don't know if this error is fixed, but I frequently encounter this error when I process Aqua satellite images. The error exampled here is from Hurricane Irma at 19:00 UTC, Sept. 10, 2017:

polar2grid.sh crefl gtiff --true-color --compress=NONE -g  wgs84_modis --fornav-D 10 -f /home/swift/1900
INFO     : Initializing reader...
INFO     : Could not find any existing crefl output will use MODIS SDRs to create some
INFO     : Creating navigation product 'longtitude_1000m'
INFO     : Creating navigation product 'latitude_1000m'
INFO     : Initializing remapping...
INFO     : Initializing backend...
INFO     : Initializing compositor objects...
INFO     : Extracting swaths from data files available...
WARNING  : Missing proper data files to create product: viirs_crefl04
WARNING  : Missing proper data files to create product: viirs_crefl03
WARNING  : Missing proper data files to create product: viirs_crefl01
WARNING  : Missing proper data files to create product: viirs_crefl08
INFO     : Creating navigation product 'longtitude_250m'
INFO     : Interpolating to higher resolution: Longtitude
INFO     : Creating navigation product 'latitude_250m'
INFO     : Creating navigation product 'longtitude_500m'
INFO     : Interpolating to higher resolution: Longtitude
INFO     : Creating navigation product 'latitude_500m'
INFO     : Creating data product 'modis_crefl01_250m'
INFO     : Creating data product 'modis_crefl01_500m'
INFO     : Creating data product 'modis_crefl04_500m'
INFO     : Creating data product 'modis_crefl03_500m'
INFO     : Remapping to grid wgs84_modis
INFO     : Grid information:
        grid_name: wgs84_modis
        proj4_definition: +proj=latlong +datum=WGS84 +no_defs
        cell_width: 0.00225
        cell_height: -0.00225
        width: 13984
        height: 9493
        origin_x: -105.183670044
        origin_y: 47.4604988098
INFO     : Running gridded scene through 'true_color' compositor
INFO     : Saving true color image to filename 'true_color.dat'
INFO     : Creating geotiff 'aqua_modis_modis_crefl01_250m_20170910_190000_wgs84_modis.tif
ERROR    : Could not create output for 'true_color'
INFO     : Creating geotiff 'aqua_modis_modis_crefl01_500m_20170910_190000_wgs84_modis.tif
INFO     : Creating geotiff 'aqua_modis_modis_crefl04_500m_20170910_190000_wgs84_modis.tif
INFO     : Creating geotiff 'aqua_modis_modis_crefl03_500m_20170910_190000_wgs84_modis.tif
INFO     : Processing data for grid wgs84_modis complete

Could someone help me out with this one? I'm little experienced at this command stuff, as it was introduced by my friend to make good images.

**Comment by djhoese** [comment]
The error messages you are getting aren't what I would expect, but let's see if we can figure this out. What files are in your `1900` directory? Polar2Grid typically needs all of the data files (250m, 500m, 1000m, geo) to be able to make the true_color composite.

What version of Polar2Grid are you using?

**Comment by KNLargadas** [comment]
I am using the latest version of Polar2Grid, while in the 1900 directory is only MOD02HKM, MOD02QKM, MOD021KM and MOD03.

**Comment by djhoese** [comment]
When you run that there should be a `.log` file left in your current directory. Could you attach that here or provide a link to it?

**Comment by KNLargadas** [comment]
Okay. I will send you it tomorrow (currently 11:36 p.m. Philippine Standard Time).

**Comment by KNLargadas** [comment]
[crefl2gtiff_20170910_190000.log](https://github.com/ssec/polar2grid/files/3765181/crefl2gtiff_20170910_190000.log)
Here

**Comment by djhoese** [comment]
Looking at the log I see:

```
[2019-10-24 08:15:55,253] : PID   2515 : DEBUG    : polar2grid.core.roles : create_output_from_scene : Backend exception: 
Traceback (most recent call last):
  File "/home/swift/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/core/roles.py", line 748, in create_output_from_scene
    output_fn = self.create_output_from_product(gridded_product, **kwargs)
  File "/home/swift/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/gtiff_backend.py", line 219, in create_output_from_product
    data = self.rescaler.rescale_product(gridded_product, data_type, rescale_options=rescale_options.copy())
  File "/home/swift/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site-packages/polar2grid/core/rescale.py", line 505, in rescale_product
    [self._rescale_data(method, data[2], good_data_mask[2], rescale_options, fill_value, clip=clip, mask_clip=mask_clip, inc_by_one=inc_by_one, clip_zero=clip_zero)],
MemoryError
```

A `MemoryError` in python means you did not have enough memory (RAM) to create the image. Do you know how much you have available on your system?

**Comment by KNLargadas** [comment]
Sorry. I will look it up tonight.

**Comment by KNLargadas** [comment]
I ran ### free###  on the terminal, and it comes like this. I only copied the most valuable data so:
mem 4847744 and the available is 4023556; and swap 998396.

P.S. I only saw it on the forums so please take it from here.

**Comment by djhoese** [comment]
I could be reading this wrong, but I think that is suggesting that you have a little over 4GB of memory. Although we are working on methods to reduce the memory needs of Polar2Grid these are not available yet, so generating some of these more involved images (like a true_color or false_color) can require a lot of memory. Do you have access to a machine with more memory?

**Comment by KNLargadas** [comment]
Um, no. Honestly I work them in VirtualBox. I just resized them when a error popped saying that there is no disk space left.

**Comment by KNLargadas** [comment]
I have been creating images fine before the error appeared. Honestly this error popped 3 times when I create the 1900Z Irma image (the error I presented), 0330Z Ewiniar image (2012, connector) and 0405 Hagibis image (on Sept. 11).

**Comment by djhoese** [comment]
I'm sorry, but I'm not sure there is much we (Polar2Grid team) can do in the near term to make this work for you. The processing simply needs more memory for these RGB images with the software as it is. Some of the memory usage may depend on what is in the actual data so memory usage may very scene by scene.

Another option, although even more on the programming side of things, would be to look at the Satpy python library which Polar2Grid is slowly moving to for all of its internal processing. We have put a lot of work in to Satpy to allow for processing to work with less memory while still using multiple cores of your system.

**Comment by KNLargadas** [comment]
Good evening sir. I have just found a solution, and that is again, resizing the disk space. The Irma problem is resolved, although the Ewiniar one hasn't. Also in 2007's Faxai at 0130Z. And there is a error which bugged me, at least for now. Might gonna explain  the error later.

**Comment by KNLargadas** [comment]
Here is the error popping out:
 /home/billyswift/polar2grid_v_2_2_1/common/ShellB3/lib/python2.7/site- 
 packages/polar2grid/compositors/rgb.py:299: RuntimeWarning: divide by zero encountered in divide
  ratio = rgb_data[compare_index] / lowres_red_data

Then after the output error, this pops in:

 ERROR:  Unexpected error during rescaling
 ERROR:  Could not output for 'modis_crefl01_500m'

I'm gonna enter the .log file that has the error presented here. This is in Faxai's 0130Z by the way.

Then, I had resized the disk space and when I checked it, it was 41 GB. But when I enter to the terminal:
 free --giga

It just pops in as 3 in available (which means 3 GB). This is in the mem section by the way.

Any ideas?

**Comment by djhoese** [comment]
This is all the same error. The "RuntimeWarning" you showed first is **not** an error, it is a warning, and in this case it is expected and harmless. If you look at the log file you will see `MemoryError` in a couple places. This is the same error I mentioned before. You don't have enough memory (RAM) in your system to do this processing reliably.

Disk space is different than and separate from RAM/memory. Changing disk space does not effect your available memory that polar2grid needs for processing. If changing these settings for your virtual machine isn't clear I would recommend doing some googling on the difference between memory and disk space.

**Comment by KNLargadas** [comment]
Ok, thanks for the advice sir. Is the 'swap' area the storage for RAM? Because this tutorial points the swap area as an RAM storage: (https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04)

**Comment by djhoese** [comment]
No. Swap is kind of like a backup for your RAM if you run out of memory, but it shouldn't be depended on. Look at these instructions (likely for an older version of VirtualBox than you have) where the first picture shows where memory can be increased:

https://askubuntu.com/a/510139

You won't be able to increase the memory of your virtual machine past what your system has. So if your real/host system only has ~4GB of memory then you will need to use a more powerful system.

**Comment by KNLargadas** [comment]
Okay. But fortunately, it ran like nothing happened. The runtime warning still persists, but at least I had it solved. I had to divide my large dev/sda1 storage (which is 47 GB) and so let it on the linux-swap area, which is /dev/sda5.

I had a lesson for today, thanks again for helping.
