### ISSUE TITLE
generate full set of Geo2Grid verified products by default

### ISSUE THREAD

**Issue by graemely** [ssec/polar2grid#229]
For v1.1, suggest generating the full set of "verified" products (e.g. those that have been checked out and are currently listed in the manual) by default. Currently only a subset is generated. I like the idea of showing the users all the images that can be created, and they can always select their own subset with `-p`.

See #227.

**Comment by djhoese** [comment]
Revisiting this in a telecon today, @graemely was ok with the current behavior so we will not be changing this in version 1.1 and it is not currently planned for a particular version in the future. Closing this as a "won't fix".
