### ISSUE TITLE
Multi-grid processing failing off and on using polar2grid-swbundle-2.3.0b1.tar.gz tarball

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#232]
There are failures occurring on operational VIIRS overpass processing when the polar2grid.sh call includes multiple grids.  Here are some facts:

1).  The problems started happening after installation of the polar2grid-swbundle-2.3.0b1.tar.gz tarball (29 October).
2).  I cannot reproduce the failures by executing my processing script outside of the operational environment.
3).  I updated the  polar2grid/glue_legacy.py by adding a line as suggested by Dave Hoese:
 +498 gridded_scene.cleanup()
but that did not resolve the problem.
4).  The errorr messages in the log files all point to intermediate files are being removed before the processing completes.  Here is a list of examples:

"RNSCA-RVIRS_j01_d20191029_t1755139_e1809274_b00001_c20191029180839561000_all-_dev.h5/RNSCA-RVIRS_j01_d20191029_t1755139_e1809274_b00001_c20191029180839561000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191029_t1755139_e1809274_b00001_c20191029180839561000_all-_dev.h5/RNSCA-RVIRS_j01_d20191029_t1755139_e1809274_b00001_c20191029180839561000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191031_t1718486_e1731367_b00001_c20191031173028865000_all-_dev.h5/RNSCA-RVIRS_j01_d20191031_t1718486_e1731367_b00001_c20191031173028865000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191031_t1718486_e1731367_b00001_c20191031173028865000_all-_dev.h5/RNSCA-RVIRS_j01_d20191031_t1718486_e1731367_b00001_c20191031173028865000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191031_t2042136_e2049204_b00001_c20191031204859042000_all-_dev.h5/RNSCA-RVIRS_j01_d20191031_t2042136_e2049204_b00001_c20191031204859042000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
RNSCA-RVIRS_j01_d20191031_t2042136_e2049204_b00001_c20191031204859042000_all-_dev.h5/RNSCA-RVIRS_j01_d20191031_t2042136_e2049204_b00001_c20191031204859042000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
RNSCA-RVIRS_j01_d20191031_t2042136_e2049204_b00001_c20191031204859042000_all-_dev.h5/RNSCA-RVIRS_j01_d20191031_t2042136_e2049204_b00001_c20191031204859042000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
RNSCA-RVIRS_j01_d20191102_t1645139_e1652207_b00001_c20191102165136378000_all-_dev.h5/RNSCA-RVIRS_j01_d20191102_t1645139_e1652207_b00001_c20191102165136378000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
RNSCA-RVIRS_j01_d20191102_t1820324_e1834459_b00001_c20191102183356782000_all-_dev.h5/RNSCA-RVIRS_j01_d20191102_t1820324_e1834459_b00001_c20191102183356782000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191102_t1820324_e1834459_b00001_c20191102183356782000_all-_dev.h5/RNSCA-RVIRS_j01_d20191102_t1820324_e1834459_b00001_c20191102183356782000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191103_t1801370_e1815505_b00001_c20191103181459319000_all-_dev.h5/RNSCA-RVIRS_j01_d20191103_t1801370_e1815505_b00001_c20191103181459319000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_j01_d20191103_t1801370_e1815505_b00001_c20191103181459319000_all-_dev.h5/RNSCA-RVIRS_j01_d20191103_t1801370_e1815505_b00001_c20191103181459319000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191031_t1808358_e1822493_b00001_c20191031182158026000_all-_dev.h5/RNSCA-RVIRS_npp_d20191031_t1808358_e1822493_b00001_c20191031182158026000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191031_t1808358_e1822493_b00001_c20191031182158026000_all-_dev.h5/RNSCA-RVIRS_npp_d20191031_t1808358_e1822493_b00001_c20191031182158026000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191101_t1751058_e1803540_b00001_c20191101180257435000_all-_dev.h5/RNSCA-RVIRS_npp_d20191101_t1751058_e1803540_b00001_c20191101180257435000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191101_t1751058_e1803540_b00001_c20191101180257435000_all-_dev.h5/RNSCA-RVIRS_npp_d20191101_t1751058_e1803540_b00001_c20191101180257435000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191101_t1930403_e1943285_b00001_c20191101194315058000_all-_dev.h5/RNSCA-RVIRS_npp_d20191101_t1930403_e1943285_b00001_c20191101194315058000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'false_color.dat'
RNSCA-RVIRS_npp_d20191101_t1930403_e1943285_b00001_c20191101194315058000_all-_dev.h5/RNSCA-RVIRS_npp_d20191101_t1930403_e1943285_b00001_c20191101194315058000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'false_color.dat'
RNSCA-RVIRS_npp_d20191102_t1732105_e1744586_b00001_c20191102174351733000_all-_dev.h5/RNSCA-RVIRS_npp_d20191102_t1732105_e1744586_b00001_c20191102174351733000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191102_t1732105_e1744586_b00001_c20191102174351733000_all-_dev.h5/RNSCA-RVIRS_npp_d20191102_t1732105_e1744586_b00001_c20191102174351733000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'true_color.dat'
RNSCA-RVIRS_npp_d20191102_t1911450_e1925585_b00001_c20191102192437499000_all-_dev.h5/RNSCA-RVIRS_npp_d20191102_t1911450_e1925585_b00001_c20191102192437499000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'false_color.dat'
RNSCA-RVIRS_npp_d20191102_t1911450_e1925585_b00001_c20191102192437499000_all-_dev.h5/RNSCA-RVIRS_npp_d20191102_t1911450_e1925585_b00001_c20191102192437499000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'false_color.dat'
RNSCA-RVIRS_npp_d20191103_t1852496_e1907031_b00001_c20191103190555060000_all-_dev.h5/RNSCA-RVIRS_npp_d20191103_t1852496_e1907031_b00001_c20191103190555060000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'false_color.dat'
RNSCA-RVIRS_npp_d20191103_t1852496_e1907031_b00001_c20191103190555060000_all-_dev.h5/RNSCA-RVIRS_npp_d20191103_t1852496_e1907031_b00001_c20191103190555060000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'false_color.dat'
RNSCA-RVIRS_npp_d20191103_t2036402_e2045123_b00001_c20191103204352685000_all-_dev.h5/RNSCA-RVIRS_npp_d20191103_t2036402_e2045123_b00001_c20191103204352685000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
RNSCA-RVIRS_npp_d20191103_t2036402_e2045123_b00001_c20191103204352685000_all-_dev.h5/RNSCA-RVIRS_npp_d20191103_t2036402_e2045123_b00001_c20191103204352685000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
RNSCA-RVIRS_npp_d20191103_t2036402_e2045123_b00001_c20191103204352685000_all-_dev.h5/RNSCA-RVIRS_npp_d20191103_t2036402_e2045123_b00001_c20191103204352685000_all-_dev.h5.log:FileNotFoundError: [Errno 2] No such file or directory: 'm_latitude.dat'
"

**Comment by djhoese** [comment]
Is this only with the `crefl` reader or with the `viirs_sdr` reader as well? What about other readers?

**Comment by kathys** [comment]
I have only seen this behavior wit the crefl reader.

**Comment by kathys** [comment]
Here is how the script is executed:
polar2grid.sh crefl gtiff --grid-coverage=0 --true-color --false-color --grid-configs /home/dbproc/dbvm/scripts/usa_grids.conf -g usa1_250m usa2_250m usa3_250m usa4_250m usa5_250m usa6_250m usa7_250m usa8_250m -f ...

**Comment by djhoese** [comment]
This should have been fixed #231 but we'll test it more to be sure (just wanted to link the github issue to the pull request).

**Comment by djhoese** [comment]
As far as we can tell this is now working fine. Closing.
