### ISSUE TITLE
Problem with CLAVRX version 3 viirs data.. 

### ISSUE THREAD

**Issue by spruceboy** [ssec/polar2grid#235]
I am using polar2grid version 2.3.0.a2 , and it does not appear to work with the clavrx cloud products.   It does work with everything else though - thanks!

I get an "Unexpected error" message when I try to make geotifs from clavrx version 3:

[jecable@nrt-polar2grid-test-cdd1 junk]$ ~/polar2grid_v_2_3_0a2/bin/polar2grid.sh clavrx gtiff --grid-coverage 0.002 -g alaska_300 -p 'cld_emiss_acha cld_height_acha cld_opd_dcomp cld_reff_dcomp cld_temp_acha cloud_phase cloud_type  '  --grid-configs /hab/pkgs/uafgina/sandy-utils/1.6.15/20191002001657/config/clavrx_geotiff_grids.grd -d /gluster/cache/gilmore/snpp/clavrx_level2/viirs/2019/10/NPP.20191030.170112.dat.gz
INFO     : Initializing reader...
INFO     : Initializing remapping...
INFO     : Initializing backend...
INFO     : Initializing compositor objects...
INFO     : Extracting swaths from data files available...
ERROR    : Unexpected error. Enable debug messages (-vvv) or see log file for details.
[jecable@nrt-polar2grid-test-cdd1 junk]$ ~/polar2grid_v_2_3_0a2/bin/polar2grid.sh clavrx gtiff  -p cld_emiss_acha -d /gluster/cache/gilmore/snpp/clavrx_level2/viirs/2019/10/NPP.20191030.170112.dat.gz
INFO     : Initializing reader...
INFO     : Initializing remapping...
INFO     : Initializing backend...
INFO     : Initializing compositor objects...
INFO     : Extracting swaths from data files available...
ERROR    : Unexpected error. Enable debug messages (-vvv) or see log file for details.

The older version I was using (2.2.1) works fine.  Am I using it wrong, or is there an issue with the newer version?

I attached the log file for reference and if you need it, I put the test dataset here: http://hippy.gina.alaska.edu/distro/clavrx_sample.tar.gz

[clavrx2gtiff_20191030_170211(1).log](https://github.com/ssec/polar2grid/files/3849340/clavrx2gtiff_20191030_170211.1.log)

Thanks!

**Comment by djhoese** [comment]
This was a bug in Satpy due to some changes in numpy and was fixed a while ago. I thought I sent you the necessary "hacks" to fix this, but maybe I had just planned on giving you a new tarball that I never did. I'll leave this open until you get a new tarball.

**Comment by spruceboy** [comment]
It is entirely possible that you sent the changes and I missed them - if so I apologize for wasting your time!   I think the only changes I have applied are related to making floating point geotifs.

**Comment by djhoese** [comment]
I'm going to close this issue for now since I think it should be fixed in the recent beta. Any clavrx-specific issues can be brought up in #236

**Comment by spruceboy** [comment]
Great, thanks again for all your help!
