### ISSUE TITLE
viirs_edr_active_fires reader lists unknown products

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#239]
tarball polar2grid-swbundle-2.3.0b4.tar.gz 

Executing polar2grid.sh viirs_edr_active_fires gtiff 
on a set of VIIR Active Fire EDR .nc files list a couple of products that I am not familiar with and which cannot be used (-p option):

``polar2grid.sh viirs_edr_active_fires gtiff --list-products -f ../active_fire_edr``
``INFO     : Initializing reader...``
``T13``
``T4``
``confidence_cat``
``confidence_pct``
``night_background``
``night_background_hires``
``power ``

Not sure what night_background or night_background_hires are?

bumi:/data/test_data/active_fire/active_fire_edr

**Comment by djhoese** [comment]
Ah interesting. This is a semi-recent feature in Satpy to have composites that are just static images (like a night time image of the Earth) that can be used as a background for other composites. I asked the other pytroll folks and it sounds like most people who cared agreed that these should not show up as "available" by default. It gives the reader the impression that these composites are of the data from the reader which they are not. I'll make a pull request to Satpy to have these hidden which should then fix this in P2G.

**Comment by djhoese** [comment]
This should now be fixed in satpy's master branch. A new build of Polar2Grid should include this fix.
