### ISSUE TITLE
VIIRS Flood remapping results in much larger area than required

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#244]
I tried remapping a standard NOAA-20 VIIRS overpass flood HDF4 product into a different projection (lcc), and  it resulted in a TIF that includes a large area that does not contain data (black).  It also took more than 3 hours.

**Command:**  polar2grid.sh viirs_edr_flood gtiff -g lcc_fit -f ../recent/*.hdf

**Logfile:**  bumi:/data/users/kathys/test_data/viirs_flood/gtiff

**Data:**  bumi:/data/users/kathys/test_data/viirs_flood/recent

The Flood Package created the left image below, and P2G the lcc_fit image on the right:

![Screen Shot 2019-12-04 at 10 28 48 AM](https://user-images.githubusercontent.com/1848019/70161196-499f7280-1681-11ea-94d1-a209d39dcc9b.png)

**Comment by kathys** [comment]
Here is the P2G default WGS84 image.  Still lots of black.  Took 11m15s.

![Screen Shot 2019-12-04 at 10 58 04 AM](https://user-images.githubusercontent.com/1848019/70163708-8b321c80-1685-11ea-8c17-b03695856a66.png)

**Comment by djhoese** [comment]
I need to make utilities for getting the longitude/latitude for any dataset so this debugging is easier and doesn't require me looking at the data. Oh maybe a jupyter notebook!

**Comment by kathys** [comment]
Tried another overpass and that one looked fine.  Must be something about that particular dataset.

**Comment by djhoese** [comment]
So looking at some basic debug information about the data file you provided, it is 15889 rows by 17490 columns. That's a lot of data so I'm not sure we can do much about the speed. It says that it goes from 13.4415N to 67.0212N which seems pretty large. Let me do some more research.

**Comment by djhoese** [comment]
Here's what the data looks like out of Satpy:

![longitude_20191203_183831](https://user-images.githubusercontent.com/1828519/70169631-cc7bf980-1690-11ea-973e-6988baa58a71.png)
![latitude_20191203_183831](https://user-images.githubusercontent.com/1828519/70169635-ce45bd00-1690-11ea-8459-1d58fa538bb0.png)
![WaterDetection_20191203_183831](https://user-images.githubusercontent.com/1828519/70169645-d00f8080-1690-11ea-8b09-c4d4a73c7610.png)

**Comment by kathys** [comment]
My comment about trying another overpass was wrong.  It also showed this large are of black at the bottom of the pass.  The first case was NOAA-20 VIIRS, the second, S-NPP VIIRS.

![Screen Shot 2019-12-04 at 3 49 32 PM](https://user-images.githubusercontent.com/1848019/70184715-060f2d80-16ae-11ea-94f3-5d98df214fb4.png)
