### ISSUE TITLE
geo2grid v1.0.1 fails when provided bare directory as input

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#261]
When creating images using Geo2Grid geo2grid-swbundle-1.0.1b0, I am able to list out the available products using -f /directory but it fails when I am actually trying to create images if  I do not provide a file pattern as input.

**For example, this works:**  
`geo2grid.sh -r ahi_hsd -w geotiff --list-products -f /data/users/kathys/geo/test_data_geo/ahi8/hsd/0630`

**but this does not:**
`geo2grid.sh -r ahi_hsd -w geotiff --num-workers 8 --method nearest --grid-configs=../../timing_grid_ex.conf -g perth_timing -f /data/users/kathys/geo/test_data_geo/ahi8/hsd/0630`

**this does work**
`geo2grid.sh -r ahi_hsd -w geotiff --num-workers 8 --method nearest --grid-configs=../../timing_grid_ex.conf -g perth_timing -f /data/users/kathys/geo/test_data_geo/ahi8/hsd/0630/*FLDK*.DAT`

**Error message:**  
"File "/data/users/kathys/geo/validation/package/try/geo2grid_v_1_0_1/lib/python3.7/site-packages/satpy/readers/ahi_hsd.py", line 329, in get_dataset
    return self.read_band(key, info)
  File "/data/users/kathys/geo/validation/package/try/geo2grid_v_1_0_1/lib/python3.7/site-packages/satpy/readers/ahi_hsd.py", line 543, in read_band
    res = self._mask_space(res)
  File "/data/users/kathys/geo/validation/package/try/geo2grid_v_1_0_1/lib/python3.7/site-packages/satpy/readers/ahi_hsd.py", line 489, in _mask_space
    return data.where(get_geostationary_mask(self.area))
AttributeError: 'AHIHSDFileHandler' object has no attribute 'area'"

**Comment by djhoese** [comment]
I looked at the data directory you are using and it has 289 files in it consisting of multiple regions/sectors. Reading all of those files at once is not supported (one sector/time per call). My guess/hope is that the log should show some kind of error message further up about not being able to read the "area" or "AreaDefinition". I'm guessing having multiple sectors loaded at the same time is confusing Satpy. That or one of the files is bad.

**Comment by djhoese** [comment]
Just did a quick test and this also fails (as expected):

```
/data/dist/geo2grid-swbundle-1.0.1b0/bin/geo2grid.sh -r ahi_hsd -w geotiff --num-workers 8 -f /data/users/kathys/geo/test_data_geo/ahi8/hsd/0630/* -vvv
```

So it isn't that a directory is provided, it is that multiple sectors are being provided.

**Comment by kathys** [comment]
Okay, the problem is that I am apparently not capable of looking in the directory that I am using.  Sorry about that.
