### ISSUE TITLE
Use new CSPP Logo on G2G and P2G Title Page

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#265]
Replace the CIMSS Logo with the new CSPP Logo on the Title pages of the P2G and G2G PDF files.

**Comment by djhoese** [comment]
Have a URL?

**Comment by kathys** [comment]
No. Should I upload it here?

**Comment by djhoese** [comment]
If you can put it on the P2G FTP location that is probably best. There isn't a public website with the full resolution version of the image?

**Comment by kathys** [comment]
No there is not.

**Comment by djhoese** [comment]
![P2G_PDF_Logos2](https://user-images.githubusercontent.com/1828519/110862994-a2e35200-8285-11eb-9200-d7c64ddfe253.png)

Remove the whitespace? Note this is the same size as the current set of logos, but the CSPP logo is square (as it should be) compared to the CIMSS logo so it left some extra whitespace.

**Comment by kathys** [comment]
It is fine with me Dave.
