### ISSUE TITLE
Port legacy Polar2Grid readers to Satpy

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#269]
These readers exist in legacy Polar2Grid but are not available in Satpy yet:

- [x] MIRS
- [x] VIIRS CREFL
- [x] MODIS CREFL

I would consider migrating the crefls as unnecessary since Satpy has a python implementation of that software (which could use some optimization).

**Comment by djhoese** [comment]
@kathys What about the DR-RTV (Dual Regression - Retrieval) algorithm reader? Is that something we still support?

**Comment by kathys** [comment]
No, we do not have to support the Dual Regression retrievals anymore.

**Comment by djhoese** [comment]
@katherinekolman In addition to your SIFT work, could you work on migrating the MIRS reader to Satpy? All of the existing code is [here](https://github.com/ssec/polar2grid/tree/master/polar2grid/mirs). I see there is some test data on `bumi:/data/test_data/old_polar2grid_data/HI_MIRS` but I'm not sure if that is still valid. @kathys do you have a recent location where Kat can get new test files?

**Comment by kathys** [comment]
I can get some to you @katherinekolman.  I will try and get it to you before the end of the day tomorrow.

**Comment by djhoese** [comment]
MODIS and VIIRS CREFL should now be used by creating the `true_color` and `false_color` composites from the `modis_l1b` and `viirs_sdr` readers.
