### ISSUE TITLE
Remove incremental release number from Validation Data tarball

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#275]
The version number scheme for the G2G Validation Data Tarball should not include the incremental number.  Most of the time this data should not change, and then we do not have to rename and re-release if there is a patch or an incremental software package update.

For instance: 
CSPP_GEO2GRID_V1.0.1_TEST_DATA.tar.gz

should just be:  
CSPP_GEO2GRID_V1.0_TEST_DATA.tar.gz

**Comment by djhoese** [comment]
@graemely What happens if the test data does need to get updated between patch releases?

**Comment by graemely** [comment]
Good question. What I forgot to mention is that in other CSPP Geo packages we have started including the date of the test data in the tarball name. For example:

`cspp-geo-grb-test-data-20191026.tar.gz `

One intended use case was that we might want to offer multiple test tarballs for the same package.
