### ISSUE TITLE
Geo2Grid enhancement of brightness temperature <--> 8-bit brightness for GOES-16->19 ABI band 7?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#278]
Hello, all -- This is a request to enhance the brightness temperature <--> 8-bit brightness conversion used for GOES-16-19 ABI band 7, the 3.9um band.   This band is strongly affected during daylight hours by reflected solar energy, and is also sensitive to energy emitted by fires on the earth's surface.  The brightness temperatures sensed in this band can far exceed the maximum value currently allowed in the Geo2Grid software -- 330K.  Our request/hope would be an update to make Geo2Grid do what is currently done by McIDAS-X for this band:

            INPUT(K)      OUTPUT(8-bit brightness value)
            ----------      ----------------------------------
                190                               255
                242                               190
                330                                 14
                400                                   0

There are three(3) segments in this "stretching table" employed by McIDAS-X: 
190-242, 242-330, 330-400.   Brightness temperatures <--> 8-bit brightnesses that fall within a given segment are determined by linear interpolation.   For example, 216K would be assigned a brightness of 223 (I think that 222.5 would get returned as 223), and 390K would be assigned a brightness of 2.   See the following McIDAS-X documentation for further information: 
      https://www.ssec.wisc.edu/mcidas/software/x/info/mcstretch_info/#details

Thank you for your considerations!

**Comment by djhoese** [comment]
This one fell through the cracks, but we will try to address as an option in a future version. We are hesitant to change it given that it would change the default result for all users.

**Comment by djhoese** [comment]
Just to make sure I wasn't missing something, I plotted this scaling in matplotlib:

![image](https://github.com/ssec/polar2grid/assets/1828519/d2584cc3-b757-403e-9031-8c88d9cbaf4c)

So this really is 3 separate linear ranges. @jpnIII how does this compare to scalings used in AWIPS? As you know we did change the scaling/enhancements used for C08/C09/C10 to be linear, but the other BT bands are based on what AWIPS 1 used to use or at least that's what I remember. I'm not sure how I feel about changing the default, but as far as if it is possible to specify this in Satpy/Polar2Grid/Geo2Grid, that should be possible with the `piecewise_linear_stretch` enhancement function. @kathys and I might have to talk about this.

**Comment by jpnIII** [comment]
Thank you for this commentary as well, Dave.

Do you have an idea when 1.2 will be released?

Later.

Sincerely,

Jim

**Comment by djhoese** [comment]
Kathy and I will discuss this today at our meeting.

**Comment by djhoese** [comment]
@jpnIII could you answer my question about the comparison of this scaling with what is done in AWIPS for this band?

**Comment by djhoese** [comment]
@jpnIII I talked with @kathys and we're OK doing this change to C07 and I can then point you to a beta tarball for you to test out. Here's the old version and the new version of C07, does it look right?

![GOES-16_ABI_RadF_C07_20180910_170031_GOES-East old](https://github.com/ssec/polar2grid/assets/1828519/9539d9b4-f131-40eb-b575-981d3fef31fd)

![GOES-16_ABI_RadF_C07_20180910_170031_GOES-East new](https://github.com/ssec/polar2grid/assets/1828519/a6b91260-dc11-4357-affa-4a357d72c7e0)

**Comment by jpnIII** [comment]
Hi Dave and Kathy – Thank you for discussing this request.

From what I can see, the new Geo2Grid treatment of this GOES-16 band07 (3.9um) image looks good!

FYI, I have attached two GOES-16 band7 images, both from 00:00:20Z  2023257.   The “ORIGINAL” image shows what band7 looked like in McIDAS-X back in 2017, and probably reflects your “old” version of C07.  The “EXPANDED” image shows what band7 has looked like in M-X since late 2017, and should reflect your “new” version of C07.   I am seeing a similar look in my two images as you have for your two images, so that’s good.

Thank you!

Sincerely,

Jim

**Comment by jpnIII** [comment]
Greetings, Lee – I have a question for you.   Do you know how AWIPS handles the display of GOES-ABI (16-19) band7 (3.9um) imagery?   Dave Hoese is interested in knowing this information.

For example, when displaying a GOES-16 -> -19 band7 image, McIDAS-X applies a stretch table, such that the 8-bit brightness (grayscale) values corresponding to input brightness temperatures are as follows:

INPUT(K)      OUTPUT(8-bit brightness value)
-------------      ----------------------------------------
      190                               255
      242                               190
      330                                 14
      400                                   0

There are three(3) linear segments in this stretch table employed by McIDAS-X:  190K-242K, 242K-330K, 330K-400K

8-bit output brightness values within a given segment are determined by linear interpolation. For example, input = 216K would be assigned an 8-bit brightness = 223 (I think that a computed value of 222.5 would get returned as 223),
and input = 390K would be assigned an 8-bit brightness = 2.   For further information, see the following McIDAS-X documentation:   https://www.ssec.wisc.edu/mcidas/software/x/info/mcstretch_info/#details

Thank you for your help!

Sincerely,

Jim

**Comment by djhoese** [comment]
@jpnIII I don't think you can attach images to github comment emails like this. You'd need to do it from the github page, not from your email. Similarly, I'm not sure any reply from Lee will get to me as he probably won't be using his Github account to add a comment here and my normal email is not on the email thread (only the github reply email).

**Comment by djhoese** [comment]
Hm actually I do see my email in the CC so maybe I'll get it.

**Comment by jpnIII** [comment]
Ok.   No big deal, Dave.   Bottom line – It looks like what you have done to update the Geo2Grid display of  GOES-16 -> 19  ABI band07 (3.9um) imagery is correct.

Thank you again for your help!

Sincerely,

Jim

**Comment by djhoese** [comment]
@scottlindstrom What is your opinion on this change? Do you know what AWIPS does (I haven't heard anything from Lee Cronce) for C07 display?

Note to both you and @jpnIII that this change will also be reflected on GeoSphere.
