### ISSUE TITLE
geo2grid.sh error message when attempting to generate composite product C02_C07?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#281]
Good day, all.    I am encountering an error message when trying to generate a GOES-17 ABI band02 (day)/band07 (night) composite image on imaginator.ssec.wisc.edu, and do not understand what I am doing wrong.   I am confident that I have added a new C02_C07 product correctly into the file:  /home/shared/bin/geo2grid_v_1_0_1/etc/satpy/composites/abi.yaml:

 C02_C07:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    prerequisites:
      - C02
      - C07
    standard_name: day_night_mix

**Here is my geo2grid.sh commandline:**

export PYTROLL_CHUNK_SIZE="4096" ; geo2grid.sh -r abi_l1b -w geotiff -p C02_C07 -g eastern_us --grid-configs geo2grid_config.conf -f /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C01_G17_s20201752330319_e20201752339386_c20201752339418.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C02_G17_s20201752330319_e20201752339386_c20201752339424.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C03_G17_s20201752330319_e20201752339386_c20201752339430.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C04_G17_s20201752330319_e20201752339386_c20201752339408.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C05_G17_s20201752330319_e20201752339386_c20201752339437.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C06_G17_s20201752330319_e20201752339392_c20201752339434.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C07_G17_s20201752330319_e20201752339397_c20201752339440.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C08_G17_s20201752330319_e20201752339386_c20201752339442.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C09_G17_s20201752330319_e20201752339392_c20201752339440.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C10_G17_s20201752330319_e20201752339398_c20201752339430.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C11_G17_s20201752330319_e20201752339386_c20201752339445.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C12_G17_s20201752330319_e20201752339392_c20201752339434.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C13_G17_s20201752330319_e20201752339398_c20201752339450.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C14_G17_s20201752330319_e20201752339386_c20201752339447.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C15_G17_s20201752330319_e20201752339392_c20201752339437.nc /arcdata/goes/grb/goes17/2020/2020_06_23_175/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C16_G17_s20201752330319_e20201752339398_c20201752339442.nc --radius-of-influence 50000 --output-filename GOES-17_ABI_RadF_C02_C07_2020175_233031Z.tif

**And here is the full path to the associated Geo2Grid logfile:**

/scratch/gops/cases/g2g/East_Pacific_actiniae/abi_l1b_geotiff_20200623_233031.log

**And here are ERROR lines of text in the Geo2Grid logfile:**

[2020-06-27 23:07:46,187] : PID  65522 : ERROR    : abi_l1b_geotiff : exc_handler : Unexpected error. Enable debug messages (-vvv) or see log file for details.
[2020-06-27 23:07:46,189] : PID  65522 : ERROR    : traceback : exc_handler : conflicting sizes for dimension 'bands': length 3 on the data but length 1 on coordinate 'bands'

Dave, I am pretty sure you already have an account on imaginator, so you should be able to look at the logfile directly, if needed.

Thank you all for your help!

Sincerely,

Jim

P.S.   Is it possible to apply a colortable to only the daytime or nighttime portion of a day/night 2-band composite image?   What I am really asking is -- for example in the case above --I might want to enhance the nighttime (GOES-17 ABI band 07) portion of each composite image by applying a colortable, presumably via add_colormap.sh.  Is add_colormap.sh able to only apply a given colortable to only a portion of a given image?   Or is there a better way to only enhance the nighttime portion of each image?

**Comment by djhoese** [comment]
So the issue here is that the day/night composite you've generated is the combination of two single band images so the output is also a single band image. Compare this to the original configuration which was the combination of the true_color RGB and a single band image to make an RGB image. The enhancement configuration is expecting an RGB dataset. You can see that in the enhancement config here:

https://github.com/ssec/polar2grid/blob/5b685494c6dcc8cb4dff0958d911dae525adb442/etc/enhancements/generic.yaml#L35

It has 3 minimums and 3 maximums specified for each RGB band. To fix this, you could change the `min/max_stretch` to be a single value.

For your other question, this is possible but not something we've ever done in Geo2Grid. Some Satpy users have done it. The general strategy is to make separate composites; one for day (ex. `colorized_c02`) and one for night (ex. `colorized_c07`). Each of these composites then has their own enhancement configuration where a colormap is added (using the `colorize` enhancement method). Your day/night composite then uses these two separate composites as inputs (`colorized_c02` and `colorized_c07`) instead of the original C02 and C07 datasets. Doing this though is currently out of scope for what Geo2Grid supports and I'm not sure how to do it myself either.

**Comment by jpnIII** [comment]
Thank you, Dave – Please see my enclosed replies.

Sincerely,

Jim

**Comment by djhoese** [comment]
Close but not quite. If you don't want to break what's already there then let's do this:

In `composites/abi.yaml`:

```
C02_C07:
  compositor: !!python/name:satpy.composites.DayNightCompositor
  prerequisites:
  - C02
  - C07
  standard_name: day_night_mix_single
```

Note the `_single` at the end of the standard_name. Then in `enhancements/abi.yaml` (or `enhancements/generic.yaml`):

```
day_night_mix_single:
    standard_name: day_night_mix_single
    operations:
      - name: stretch
        method: !!python/name:satpy.enhancements.stretch
        kwargs: {stretch: crude, min_stretch: 0.0, max_stretch: 1.0}

```

**Comment by jpnIII** [comment]
Hi Dave – I tried this suggestion.   It appears to work properly.  ☺

Thank you for your help!

Sincerely,

Jim
