### ISSUE TITLE
Slight errors in polar2grid linear example?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#282]
Hello -- Just wanted to ask if there are a couple of typos in the following example, that can be seen in the Linear rescaling example at:  

https://www.ssec.wisc.edu/software/polar2grid/rescaling.html?highlight=rescale#brightness-temperature 

Example (10-255 from 173-300):

m = (250.0 - 10.0) / (300.0 - 173.0) = 1.90
b = 10.0 - 1.90 * 300.0 = -560.0
rescale_data = 1.90 * data + -560.0

Shouldn't this be instead:

m = (255.0 - 10.0) / (300.0 - 173.0) = 1.9291338
b = 10.0 - 1.9291338 * 173.0 = -323.74014
rescale_data = 1.9291338 * data + -323.74014

Thank you!

**Comment by djhoese** [comment]
Thanks. I've created #283 as a solution with your fixes. I think it is right now.
