### ISSUE TITLE
Add option to remove NOAA-20 VIIRS DNB stray light aggregation region in images

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#284]
NOAA-20 VIIRS DNB data includes stray light correction artifacts along the left edge (right image edge) of each scan that can dominate nighttime images created with P2G.  After trying lots of ways to alleviate this problem, we finally decided to set the SDR Radiance array values to the fill values (-999.8) for elements of each line 3900-4064.  This essentially trims the affected area from the images.

Nick Bearson wrote a .nim program to do this:  https://gitlab.ssec.wisc.edu/nickb/nostraylight

For implementation you would want to create a duplicate SDR file to work on so that the original SDRs whould not be modified.  This is only for creating images.  

Also  note that there is still overlap between passes even after trimming, so you will still get full global coverage every day.

**Comment by djhoese** [comment]
So the desired solution would be a flag to mask out these columns and not to add support for Nick's code nor support for a separate masked SDR file?

**Comment by kathys** [comment]
Interesting question.  I don't think we want to be in the business of producing edited SDRs with P2G.  However, if people wanted to produce Radiances for any of the P2G supported writers (I guess I am thinking of HDF5 files), then they can produce trimmed files.  You can definitely use Nick's code for that.

**Comment by djhoese** [comment]
I ask because this is not hard to do in Satpy once we are at the processing stage of "I have a full array of data, now mask it". But if users want to run Nick's code and produce a new file and *then* give it to P2G with a different filename, it probably wouldn't work out of the box. Without supporting a separate file, it comes down to:

```
# I want data for all rows and columns up to but not including column 3900
data = data[:, :3900]
```

There is no need to process these columns so if we cut them off we save time and space. Rather than setting them to a fill value inside P2G/Satpy.

**Comment by kathys** [comment]
Much better option.  No need to use Nick's code.  We may want to distribute his code as a CSPP utility instead.  I would not plan to support any new files.

**Comment by djhoese** [comment]
@kathys What was the final outcome of this? Isn't this something users request on the SDR processing now? Do we still want this flag in P2G?

**Comment by kathys** [comment]
I use Nick's code, which works fine.  I do not think this is a P2G issue.
