### ISSUE TITLE
GeoTIFF alpha band default in P2G 3.0

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#296]
Polar2Grid 3.0 will be changed to create GeoTIFFs with alpha bands.  I think this is fine and makes it consistent with Geo2Grid.  The only thing I want to ensure is that there is a way for current users to produce the same GeoTIFFs as the current and past versions did, which did not include the alpha channel.  So in other words, I would like them to be able to create 8 bit 1-255 gray scale images with 0 being used as the fill value.

**Comment by djhoese** [comment]
I'll mention it here for the record even though we talked about it at our last meeting, with the `--fill-value 0` flag a user will be able to create a 0-255 image but 0 the data will have the same meaning as 0 the fill value. I'll have to see if I can patch satpy (trollimage) to allow for this kind of functionality that you want where 0 is the only fill value and 1-255 is valid data.

**Comment by djhoese** [comment]
This should be the default in trollimage from now on. Closing as I automatically pull in the newest version of trollimage.
