### ISSUE TITLE
Possible doc typo

### ISSUE THREAD

**Issue by dasantek** [ssec/polar2grid#298]
On this page:
https://www.ssec.wisc.edu/software/polar2grid/writers/gtiff.html

under --dtype the default is listed as: (default: ‘uint1’ 8-bit integer)

Shouldn't that be 'uint8' ?

Also, it has it in single quotes, where other defaults on the page use double quotes. Is there a difference between single and double quotes?

**Comment by djhoese** [comment]
Thanks, nice catch. The uint1 was the old way we addressed these dtypes (real4, uint1, etc). The new dtypes map to data types in the numpy library and looks like I forgot to update the help string.

In python there is no difference between single and double quotes and there is no difference for how these defaults are documented. The cause of this was that the dtype default was hand written by me and the others were auto-generated by a utility library which chose double quotes.
