### ISSUE TITLE
Trouble outputting VIIRS composite

### ISSUE THREAD

**Issue by dasantek** [ssec/polar2grid#299]
Before providing input/output examples, I'll describe the problem I'm seeing to as there may be a simple answer.

1. The GeoTIFF output does it exactly what I want: outputs 'uncompressed', 'btemp', 1-byte data. However, there may be something about the way the TIFF is being written I don't understand: When there is missing data at the top of the reprojected image, those blank lines do not seem to be present. Is there a TIFF tag that I'm not using or interpreting correctly. If the VIIRS swath intersects with the top of the image, all is good. Interestingly, the output GeoTIFF is the size I would expect regardless if the top of the image contains missing data or not. So, this could all be in my TIFF reader.

2. Since #1 isn't working out, I tried 'binary' output. However, is appears that the default output is not 'btemp', but I couldn't find the option in the doc to specify 'btemp'. 

Suggestions?

**Comment by djhoese** [comment]
I'm not sure I'm fully understanding the issue, so I'll ask some questions and make some guesses that you can investigate.

1. Are you telling it to be uncompressed? I think the default is LZW compressed.
2. What "grid" are you resampling to? The default "wgs84_fit"?
3. It sounds like the overall issue is based on how resampling is handling missing data. If there is missing **navigation** data (lons/lats) then resampling won't include those pixels when determining the output grid size (for dynamic grids). If the lons/lats are good, but the data is missing it should include the space for those invalid pixels in the output grid (again, for dynamic grids).
4. How do you know that blank/missing lines aren't present? Do you mean the pixels are cut out of the resulting geotiff or that the pixels are all black?
5. What do you mean by "the default output"? Do you mean the filename?

**Comment by dasantek** [comment]
Yes, my description was a little vague, but I think I tracked down the problem. Essentially, it came down to your question #4. In the resulting the geotiff, the blank lines at the top of the image are all black. However, my TIFF reader does not decode blank lines at the top. I suspect the TIFF writer does some kind of tiling and writes those zeros somewhere else; my TIFF reader erroneously reads the file as a continuous raster, and therein lies the problem! The easy fix: run 'convert' on the polar2grid output TIFF file to another TIFF file, and voila everything works! Thanks!

**Comment by djhoese** [comment]
That works? The geotiffs should be striped by default unless you specify the `--tiled` option:

https://github.com/ssec/polar2grid/blob/8be3efdfdf3792235f4a2a5dd5105f4aebea1ecc/polar2grid/gtiff_backend.py#L263-L264

**Comment by dasantek** [comment]
I was thinking 'tiling' and 'striping' was the same thing. That being said, I do recall working with TIFF files where the stripes were not necessarily in raster order. So, by using convert, I suspect the image magick intermediate file format was in raster order; then rewriting a TIFF would also be.

**Comment by djhoese** [comment]
What tool are you using to view these geotiffs that doesn't use the TIFF library to read them?

Striping is storing the data on disk row by row. Tiling is storing the data on disk one 2D tile at a time. So the below image would be stored with all the 0s first, then the 1s first, and so on (depending on the tile size chosen by the user):

```
000111222
000111222
000111222
333444555
333444555
```

**Comment by dasantek** [comment]
I wrote some code about 30 years ago to read TIFF based on the spec; probably before a library was available!

**Comment by djhoese** [comment]
Ok then there is definitely a chance of an interleaving option that your reader doesn't support that may be GDAL's default (Satpy is using the rasterio python library which uses GDAL underneath to write geotiffs).

**Comment by djhoese** [comment]
I think we got a solution for all your original problems so I'm going to close this. Any similar or new issues should be created as a new bug report. Thanks.
