### ISSUE TITLE
Add caching option to add_coastlines

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#303]
Pycoast, the library we use for the add_coastlines script, has a function that can cache the coastlines that are drawn. See https://pycoast.readthedocs.io/en/latest/api/pycoast.html#pycoast.cw_base.ContourWriterBase.add_overlay_from_dict for details. If we refactored the add_coastlines script to put all available options in a dictionary and then pass them to this function (instead of individual calls). This should have a huge performance impact on the script when used on things like Geo2Grid output. Polar2Grid will not really benefit unless it is used on a static grid (one that doesn't change from swath to swath).

**Comment by jcovington16** [comment]
So just to reiterate so I understand better... You want to cache all available options into a dictionary of its own and then pass that dictionary into the function so it can call all the arguments in that dictionary?

**Comment by jcovington16** [comment]
Seeing all the different arguments you have listed are there some cases where the user won't need every option available? Throwing these arguments into a dictionary for them to be passed in automatically sounds like it will be easier for the use... but what if there are options I want to not use in a particular use case. I guess what I'm asking is do you still want the user to use these arguments, but index through the dictionary to pass them into the function? Just trying to understand better so I can help.

**Comment by djhoese** [comment]
From the user's perspective the command line arguments in `add_coastlines` will not change. The reason things have to be thrown into a dictionary is because the method in pycoast (`add_overlay_from_dict`) takes a dictionary. The dictionary will only need the options added for the ones that the user specifies as the defaults (in `add_overlay_from_dict`) are to not perform those actions if they are not present. It is essentially offloading the work from the add_coastlines command line arguments to the `add_overlay_from_dict` function.

**Comment by jcovington16** [comment]
So from reading the pycoast documentation which I will paste in here for you describes taking in a configuration file as well if that is an option. Two things can happen. I can create a script to have the user throw in the options they want for each argument that requires it, throw it into a configuration file and have that file passed in or throw it in a dictionary like you are requesting and pass in that dictionary. Either way there needs to be something that will gather the options the user wants so that it can be stored in the dictionary since add_coastlines will not change. 

Also to clarify you want to include the add_overaly_from_dict() inside of the add_coastline script to pass into your main()

[https://pycoast.readthedocs.io/_/downloads/en/latest/pdf/](url)

**Comment by jcovington16** [comment]
My apologies. I've missed spoke was not on the same page. I totally understand what needs to happen. I just forked the repo and will get started on it if that's cool?

**Comment by djhoese** [comment]
If you are willing to help the project that's great. Go ahead. Could you tell me a little bit about where you're working and why you're willing to help? Not that I will turn down help, but are you just hoping for more experience or do you use Polar2Grid/Geo2Grid in your work/studies?

The work that needs to be done, put another way, is to change all of the individual calls to `add_X` in the add_coastlines script so that it creates a dictionary instead. At the end of the script and creating this dictionary, the dictionary will be passed to `add_overlay_from_dict` to do the actual work.

**Comment by jcovington16** [comment]
Unfortunately I don't use this product, but I am just a developer looking to develop my skills outside of work. I want to contribute more to opensource projects and just overall learn more. If you prefer more experience then I wont touch anything.

**Comment by djhoese** [comment]
If you'd like to try to tackle this then that's great, go for it. I find that contributing to open source projects is more interesting in the long run if you work on projects that you yourself use. If you'd like to work on a pull request for this then I have no problem with that. We can go through the normal pull request review process for any requested changes if you're concerned about experience or code quality. Thanks for your interest in helping regardless of what you decide to do.

**Comment by jcovington16** [comment]
It's ok. I'll pass so you guys can feel more comfortable with someone who actually use the product. I can see if you guys have something that don't require too much change.

**Comment by djhoese** [comment]
Some basic tests with this caching option show that generating coastlines, borders, rivers, and adding a grid takes ~6s on my machine with no caching, ~7s to generate the image and cache it, and ~4.4s to generate the same image using the cache. Not great. Not terrible.

**Comment by djhoese** [comment]
Not sure how I forgot this, but this should be available now (see #368). Closing...
