### ISSUE TITLE
Deprecate `--grid-coverage` flag in Polar2Grid

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#312]
We need to discuss whether or not to include this flag in Polar2Grid 3.0. Polar2Grid <3.0 currently offers a `--grid-coverage X` flag which says "if the output grid doesn't have X% of the grid filled with data, don't output the file. This is a problem for P2G 3.0 because we are using dask which operates on array **chunks**. We can't know if the entire grid is covered unless we compute the entire grid and hold it all in memory at once. This removes all benefits of dask for the second half of process (mostly writing to disk) and would use a lot of memory.

One option would be to use polygon math based on only the lon/lats, similar to how day/night coverage is computed, to see what the coverage is before hand. I'm not entirely sure how to do this, but I'll see.

Just wanted to create this to make sure it was in the discussion for P2G 3.0.

**Comment by kathys** [comment]
I use this option alot, and so does GINA.  Does P2G Version 3.0 have any kind of threshold or will it create images no matter what?   Both GINA and I use this option to lower the threshold.  When I use it, I set it to  "zero".

**Comment by djhoese** [comment]
It has no threshold. It will always create the output image even if it is empty (no valid data).
