### ISSUE TITLE
True Color image differences

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#325]
Installed the polar2grid-swbundle-20210324-121314.tar.gz tarball and created a true color image from a test data set that I have on _bumi:/data/users/kathys/test_data/viirs_asia/sdr_.  When I compare with the original images that I made using Polar2Grid Version 2.3 I noticed these differences

- [ ]  The background is white (or transparent). It was previously black.
- [ ]  The images is sharper.
- [ ]  There are "holes" in the image.
- [ ]  The enhancement is different.

Here are full resolution cutouts from a section of the image created using the P2G Version 2.3 and P2G Version 3.0 software.

Version 2.3
![P2G_v2 3](https://user-images.githubusercontent.com/1848019/112509404-6ec86080-8d5e-11eb-9846-d45ee1fafaba.png)
Version 3.0
![P2G_v3 0](https://user-images.githubusercontent.com/1848019/112509443-77b93200-8d5e-11eb-9d56-d61e2fc81a31.png)

**Comment by djhoese** [comment]
@kathys Can you verify that the background isn't actually transparent? That's what I'm seeing in the images I'm generating. If you open the images in Preview on OSX there should be a Preferences option to change the background color and/or remove it. If you specify the `--fill-value 0` flag on the command line then you should get a black background. The default behavior (we've discussed this a couple months ago) is to create an "alpha" channel on these RGBs to control the transparency (transparent for invalid pixels).

**Comment by kathys** [comment]
Verified that background is transparent.  I do remember talking about this; I just need to remember to put this info into the documentation.

**Comment by yukaribbba** [comment]
I would say I prefer the 2.3 version. It will give me more latitude when processed by Photoshop or other image tools.

**Comment by djhoese** [comment]
@yukaribbba Yes, we agree. This issue is meant to address issues/differences in the current internal beta version of P2G 3.0.

**Comment by djhoese** [comment]
Just to tie up this issue, @kathys has done a lot of investigating into this and the images are now the same with current development versions of the software (polar2grid, satpy, trollimage, etc).
