### ISSUE TITLE
Alternative filename for FY-3D MERSI-2 L1B dataset

### ISSUE THREAD

**Issue by yukaribbba** [ssec/polar2grid#331]
According to the documentation on SSEC website, L1B datasets should be like **tf{start_time:%Y%j%H%M%S}.{platform_shortname}-{trans_band:1s}_MERSI_1000M_L1B.{ext}**, for example:

tf2019233172521.FY3D-X_MERSI_0250M_L1B.HDF 
tf2019233172521.FY3D-X_MERSI_1000M_L1B.HDF
tf2019233172521.FY3D-X_MERSI_GEOQK_L1B.HDF 
tf2019233172521.FY3D-X_MERSI_GEO1K_L1B.HDF

But also there's another way CMA name them:
FY3D_MERSI_GBAL_L1_20200209_1630_0250M_MS.hdf
FY3D_MERSI_GBAL_L1_20200209_1630_1000M_MS.hdf
FY3D_MERSI_GBAL_L1_20200209_1630_GEO1K_MS.hdf
FY3D_MERSI_GBAL_L1_20200209_1630_GEOQK_MS.hdf

This type is used on CMA's own data distribution website. However, PG 2.3 can't recognize it. Here's one scene for test.
[https://drive.google.com/drive/folders/1Dg4LY8J87syi1_MiBceXDaWsdETK48lE?usp=sharing](url)

So it would be very helpful if we add this in the future updates. Thank you!

**Comment by djhoese** [comment]
Thanks for the suggestion @yukaribbba. I haven't downloaded the files yet, but do you know if they have the same internal structure as the files currently supported by P2G?

**Comment by yukaribbba** [comment]
@djhoese They worked perfectly in PG after renamed by manual's scheme. So I think they are the same.

**Comment by yukaribbba** [comment]
@djhoese Something wrong with the sharing option. It is accessible now without request or code.

**Comment by djhoese** [comment]
@yukaribbba If the files worked with renaming then this should be a pretty simple change in Satpy to accept these files. Since I see you've made issues on Satpy before, how would you feel about making a pull request to Satpy to change the YAML file for the mersi reader so it can accept these files?

**Comment by yukaribbba** [comment]
@djhoese Sounds great!

**Comment by djhoese** [comment]
Closing this as it isn't something Polar2Grid can fix.
