### ISSUE TITLE
Testing new composite products within Geo2Grid ?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#348]
Hello, all -- I know that for generating a new Geo2Grid product, I can enter its definition into the core release satpy/composites/abi.yaml  file.  But if I just have something I want to try out experimentally -- without risk of breaking the core release .yaml file -- is there a way to have a "local"  account .yaml file, that geo2grid.sh will be able to find?   For example, is there such a thing as $GEO2GRID_PATH, or some such environment variable, that could be modified to include the name of my local directory, so that geo2grid.sh would be able to find my "local" .yaml file ?   I  hesitate to edit the core release .yaml file when in experimental mode, at the risk of screwing things up.   Once the new product is ready, of course, then I am good with entering its definition into the core abi.yaml file.

Thank you for your thoughts on this!

Sincerely,

Jim

**Comment by djhoese** [comment]
Hi @jpnIII. This PATH-like variable does not currently exist in the latest release of Geo2Grid, but will exist in future versions as recent changes to Satpy (by me) have allowed for this.

One option you have is to keep your YAML files relative to your current working directory. So if you are in `/your/path` and you have composite configs in `/your/path/composites/abi.yaml` then Satpy/G2G should be able to find them. This is untested, but is theoretically how it is supposed to work.

**Comment by jpnIII** [comment]
Thank you, Dave – And thank you also for the future inclusion of the PATH-like variable!

Enjoy the beautiful Spring weather!

Sincerely,

Jim

**Comment by djhoese** [comment]
Looks like we found a workaround for your original issue. In future versions there will be a Satpy-compatible way of customizing/adding additional configuration directories, but there is also the `etc/` directory in the Geo2Grid tarball that can have customizations made to it. Of course, this modifies the G2G builtins that you could still break but at least it isn't Satpy.
