### ISSUE TITLE
A question about temperature difference imagery in geo2grid.sh, and a possible typo in a core composite geo2grid product name?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#353]
Greetings, all -- 

1.)  When compositing the difference between, for example, GOES ABI band8 and band10 (8 - 10), can you tell me what the default product range is for the output imagery (e.g., what difference will get assigned an output product brightness =0, and what difference will get assigned an output product brightness = 255)?   When I took a look at the following code:

      https://github.com/ssec/polar2grid/blob/master/etc/enhancements/generic.yaml#L2-L10

I noticed a composite product named:   "temperature_differenece"   that had a minimum = -10, and a maximum = 10

So is this the code that will get used when I take ABI band 8 - ABI band 10?    

2.)  You might have noticed in #1 above, that the title is misspelled -- "temperature_differenece" should probably be "temperature_difference"   It likely does not matter, though, so long as the code that uses this product definition invokes the proper name.    :)

Thank you very much!

Sincerely,

Jim

**Comment by djhoese** [comment]
1. Short answer: No. That is used for the "ifog" product in Polar2Grid. It *could* be used if you set your composite's `standard_name` to `temperature_difference` (as described in the other issue). Note that the entry is for `standard_name` not the produce name (`name`).
2. Correct.
3. Check the log file that is created. Although kind of cryptic, there should be output about what enhancement operations are being used. It may not say what you expect since most likely the enhancement being used is a default "stretch" operation that defaults to (when no kwargs are provided) scaling based on the min and max of the data. You'll have to configure your own enhancement for the differences you want. You could make up your own standard_name even (ex. `standard_name: bt_difference`) and specify it for the composite(s) and the enhancement.

**Comment by jpnIII** [comment]
Thank you, Dave!    Concerning your answer to #3 -- Yes, we did find some of the information you are talking about (see the cut/paste below).   Our product consists of C07, C05 and C08-C10.  I see information about a crude stretch being applied near the end of the cut/paste log text.  Presumably, the stretch does not happen until after the product itself has been computed from the C07, C05 and C08-C10 data, using the computed min/max composite values found via some composite formula?    Speaking of which, do you know what the composite formula would be, based on the composites/abi.yaml product description I added to the end of this note?   Thinking about this further, perhaps with a composite product like this, there might not be a way to know what the min/max C08-C10 difference is, because that computation is itself contained within the composite computation.  Am I making sense here?

Thank you, sir.

Sincerely,

Jim

P.S.   Dave, I am sorry to be such a pain in the you-know-where.   Truthfully, I don't like to bother you so much.  I guess/hope that perhaps these questions might help your team have an idea of what other users may be curious about, and might also help when you update your user's guide in the future.  Thank you.

[2021-05-25 20:48:40,668] : PID  26830 : DEBUG    : satpy.scene : unload : Unloading dataset: DatasetID(name='C07', wavelength=(3.8, 3.9, 4.0), resolution=2000, polarization=None, calibration=     'brightness_temperature', level=None, modifiers=())
6762 [2021-05-25 20:48:40,668] : PID  26830 : DEBUG    : satpy.scene : unload : Unloading dataset: DatasetID(name='C05', wavelength=(1.58, 1.61, 1.64), resolution=1000, polarization=None, calibrati     on='reflectance', level=None, modifiers=())
6763 [2021-05-25 20:48:40,668] : PID  26830 : DEBUG    : satpy.scene : unload : Unloading dataset: DatasetID(name='_plume_diff_night_dep_0', wavelength=None, resolution=2000, polarization=None, cal     ibration='brightness_temperature', level=None, modifiers=())
6764 [2021-05-25 20:48:40,668] : PID  26830 : DEBUG    : satpy.writers : read_writer_config : Reading ['/home/shared/bin/geo2grid_v_1_0_2/lib/python3.7/site-packages/satpy/etc/writers/geotiff.yaml'     ]
6765 [2021-05-25 20:48:41,015] : PID  26830 : DEBUG    : satpy.writers : apply : Enhancement configuration options: [{'name': 'stretch', 'method': <function stretch at 0x7f4633cdbef0>, 'kwargs': {'     stretch': 'crude'}}, {'name': 'gamma', 'method': <function gamma at 0x7f4633d07440>, 'kwargs': {'gamma': [1.0, 1.0, 1.0]}}]
6766 [2021-05-25 20:48:41,015] : PID  26830 : DEBUG    : trollimage.xrimage : stretch : Applying stretch crude with parameters {}
6767 [2021-05-25 20:48:41,029] : PID  26830 : DEBUG    : trollimage.xrimage : gamma : Applying gamma <xarray.DataArray (bands: 3)>

 plume_diff_night:
    description: >
      Plume RGB, for GOESR: NASA, NOAA
#   references:
#     None.   
    compositor: !!python/name:satpy.composites.GenericCompositor
    prerequisites:
      - name: C07
      - name: C05
      - compositor: !!python/name:satpy.composites.DifferenceCompositor
        prerequisites:
          - name: C08
          - name: C10
    standard_name: plume_diff_night

**Comment by djhoese** [comment]
I think the confusion here stems from where/when the enhancements are applied and what your composite actually "is" before it is enhanced. You made your composite definition so (R, G, and B) are `(C07, C05, C08-C10)`. These bands are put together and just "live" as three joined arrays of floating point numbers with an overall shape of (3 bands, Y rows, X columns). These values aren't touched until enhancement time so what the temperature difference is doesn't really matter as long as you configure your enhancement the way you want.

With the enhancement that the log is showing, it is doing a "crude" stretch (which you've used before) but with no keyword arguments. This means that by default it will scale each channel in the (R, G, B) composite separately based on their min and max values. You could specify the min and max stretch for each band if you wanted like you have for other composites. So I think the main question is how do you want it enhanced?

One thing I'm not sure of is if it is possible to do a crude stretch on only the B channel of the RGB and leave the others untouched. If this is what you're hoping for I'd need to look it up.

**Comment by jpnIII** [comment]
Hi Dave – Thank you.   A very nice email!   I think I follow what you are saying.


1.)    Do you know if the min/max range for each (R, G, B) component is computed over just the image domain you are working with, or are the ranges computed over the entire Level-1b domain (i.e., the entire FD, CONUS, M1 or M2 domains)?

2.)    Unless I am mistaken, then, if you DO NOT specify brightness temperature ranges for each component within your enhancements/abi.yaml file, you run the risk of each composite image looking slightly different, just because the temperature range changes slightly from one image time to the next.  So for clean (i.e., “apples to apples”) comparison between different composite images, it would be best to establish fixed ranges for each component in an RGB, right?  Not saying anything is wrong – just want to make sure I understand.

Thank you again for all of your help, Dave!

Sincerely,

Jim

**Comment by djhoese** [comment]
1. It is for whatever data is being saved to disk. So if you cropped or resampled the original data, then it should only be considered that cropped/resampled data.
2. Yes, exactly. The default enhancement used in Satpy is kind of just a convenience so you get *something* in your image, but it is almost always not what you want as an end result and an enhancement specific to that RGB should be created.

**Comment by jpnIII** [comment]
Thank you for your quick replies, Dave.  Sounds good!

Take care.

Sincerely,

Jim
