### ISSUE TITLE
'cannot execute binary file' error on a Mac OSX  for Geo2Grid

### ISSUE THREAD

**Issue by tpletzer** [ssec/polar2grid#357]
Hi,

I am new to using Geo2Grid and saw that its meant to be very similar to Polar2Grid. 

I followed the installation instructions on: https://www.ssec.wisc.edu/software/geo2grid/installation.html 
and obtained the error: cannot execute binary file
when running the command:
$GEO2GRID_HOME/bin/geo2grid.sh -r abi_l1b -w geotiff --list-products -f ~/data/

I tried following the information from an older issue using:
pip install --user --trusted-host larch.ssec.wisc.edu --extra-index-url http://larch.ssec.wisc.edu/simple/ polar2grid[awips,gtiff,remap,utils]

and obtained the following errors:
ERROR: Could not find a version that satisfies the requirement polar2grid.core[all] (from polar2grid[awips,gtiff,remap,utils]) (from versions: none)
ERROR: No matching distribution found for polar2grid.core[all] (from polar2grid[awips,gtiff,remap,utils])

I know that Geo2Grid is meant for Linux but any support would be appreciated!

**Comment by djhoese** [comment]
From the top of the page:

> The software bundle is only supported on CentOS6-compatible systems, but may work on other Linux systems as well.

The Geo2Grid bundle, similar to our Polar2Grid releases, is only meant to run on CentOS-like systems. It will not run on Mac/OSX, Windows, or some forms of Unix systems.

However, we recently attempted an additional and experimental installation method to support the [Beginner's Guide to GOES-R Series Data](https://www.goes-r.gov/downloads/resources/documents/Beginners_Guide_to_GOES-R_Series_Data.pdf). You can see some installation instructions in that PDF or in our README:

https://github.com/ssec/polar2grid#other-installation-methods

As it says in the README above, the recommended way of doing this is using a anaconda or miniconda environment: https://docs.conda.io/en/latest/miniconda.html
