### ISSUE TITLE
"Smearing" along northern edge seen with display of GOES-16 ABI band13 Mesoscale sector M2 imagery?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#363]
Hello, all -- When using geo2grid.sh to display a GOES-16 ABI band13 Mesoscale sector M2 image, we encountered a situation where there was a "smearing" of the imagery along its northern edge (see attached image).   Is there something we are doing wrong?  The geo2grid.sh and other commands we used are shown below.  The smearing is a zone a little less than 1 degree of latitude wide, on the northern edge of the imagery, that runs from west to east, passing over Lake Winnebago.

Thank you for your help!

Sincerely,

Jim

![GOES-16_ABI_RadM2_C13_2021210_060857Z (002)](https://user-images.githubusercontent.com/2246039/127532721-86c8fc70-79f2-478a-990e-3e52d896387a.png)

geo2grid.sh  -r abi_l1b -w geotiff -p product -g eastern_us --grid-configs geo2grid_config.conf -f /arcdata/goes/grb/goessatnum/ccyy/ccyy_MM_DD_ddd/abi/L1b/sector/OR_ABI-L1b-sector-MquesCquesques_Gsatnum_sccyydddhhmmasterisk.nc --radius-of-influence 50000 --output-filename tif_file
p2g_grid_helper.sh eastern_us         -90                   45                    650                       -650                  1200        1000   > geo2grid_config.conf
add_colormap.sh GA20P1_255BLACK_colortable.txt tif_file
add_coastlines.sh tif_file dashdashadd-coastlines dashdashcoastlines-resolution=h --coastlines-level 5 dashdashcoastlines-outline=blue dashdashadd-borders dashdashborders-resolution=f dashdashborders-outline=blue -o png_file

**Comment by djhoese** [comment]
Sorry about this Jim. I thought I answered this issue a long time ago.

This is a result of the "--radius-of-influence" parameter with nearest neighbor resampling. The value tells geo2grid/satpy/pyresample how far to look (in geocentric meters) for a valid input pixel to fill in an output pixel. Satpy/pyresample try to determine the best value for you based on the input grid and output grid. I think I've improved this guess in recent versions of Satpy that may not have been released yet in a Geo2Grid release.

You could try playing around with values between 10000 and 50000 (or less or more) and see how that changes the end result. The issue with making it too large is you get results like you are seeing on the edge of the data. The issue with making it too small is that depending on the projection of the input and output you can end up with cases where no valid pixels are found within the distance and end up with weird circular patterns of missing pixels in your final image.

**Comment by jpnIII** [comment]
My apologies for not remembering, Dave.   Yes, I recall those strange circular patterns now that you mention them.   You recommended the use of 50000 to mitigate the patterns several years ago.  But until now, we did not run into a domain boundary case like this.  We will make the search radius a user-defined value in our Geo2Grid processing.

Thank you again – This is helpful information!

Sincerely,

Jim
