### ISSUE TITLE
Geo2Grid Rocky Linux testing

### ISSUE THREAD

**Issue by graemely** [ssec/polar2grid#402]
Follow the instructions in the [online Geo2Grid documentation](https://www.ssec.wisc.edu/software/geo2grid/) to install the software on a Rocky machine, run the test case, and check the output.

@djhoese @kathys is there any other functionality that should be tested? Gridding?

**Comment by djhoese** [comment]
The "proper" answer is that yes everything should be tested. The "logical" (?) answer is that Satpy provides all the functionality for Geo2Grid/Polar2Grid at this point and is testing on Ubuntu, Windows, and MacOS. If it fails on Rocky I'd be very surprised. That said, our dev system "bumi" is currently CentOS 7 until we can release Polar2Grid 3.0, then it will be upgraded to Rocky and all of our integration tests will be run. Those will point out any Rocky related failings.

**Comment by graemely** [comment]
Per discussion with @djhoese, we will ask Marco to run the test case, and later when bumi is upgraded to Rocky Dave will run the integration tests.

**Comment by mjkpolo** [comment]
I'm getting this when I run the test case:
```console
[mkurzynski@espresso work]$ geo2grid.sh -r abi_l1b -w geotiff --num-workers 8 --progress  -f ../input
INFO     : Sorting and reading input files...
INFO     : Using default product list: ['C01', 'C02', 'C03', 'C04', 'C05', 'C06', 'C07', 'C08', 'C09', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'true_color', 'natural_color']
INFO     : Loading product metadata from files...
WARNING  : Required file type 'c04' not found or loaded for 'C04'
WARNING  : Required file type 'c11' not found or loaded for 'C11'
WARNING  : Required file type 'c15' not found or loaded for 'C15'
WARNING  : Required file type 'c06' not found or loaded for 'C06'
WARNING  : Required file type 'c10' not found or loaded for 'C10'
WARNING  : Required file type 'c12' not found or loaded for 'C12'
WARNING  : Required file type 'c08' not found or loaded for 'C08'
WARNING  : Required file type 'c16' not found or loaded for 'C16'
WARNING  : Required file type 'c13' not found or loaded for 'C13'
ERROR    : Unexpected error. Enable debug messages (-vvv) or see log file for details.
```
I have attached the error log: [abi_l1b_geotiff_20181219_174533.log](https://github.com/ssec/polar2grid/files/8099846/abi_l1b_geotiff_20181219_174533.log)

**Comment by graemely** [comment]
The log indicates that it is not finding `libnsl.so.1`, which is the same problem that was reported with some CSPP LEO software on Rocky. Apparently that file is not included in RH8. 

Tagging @rayg-ssec, who I think encountered this problem in ShellB3.

```
Traceback (most recent call last):
  File "/data/users/mkurzynski/geo2grid_v_1_0_2/lib/python3.7/site-packages/yaml/constructor.py", line 533, in find_python_name
    __import__(module_name)
  File "/data/users/mkurzynski/geo2grid_v_1_0_2/lib/python3.7/site-packages/satpy/writers/geotiff.py", line 25, in <module>
    import rasterio  # noqa
  File "/data/users/mkurzynski/geo2grid_v_1_0_2/lib/python3.7/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
```

**Comment by djhoese** [comment]
@mjkpolo Do you have access to the server `bumi`? I'll try getting you a "modern" Geo2Grid tarball next week that should hopefully work for your tests.

**Comment by mjkpolo** [comment]
Sounds good

I'm getting
```console
(mkurzynski@bumi) Password:
Connection closed by 128.104.108.227 port 22
```
on bumi

**Comment by djhoese** [comment]
Ok, thanks for checking. I'm getting a version of Geo2Grid ready for some other folks in the building, hopefully ready this week. When it is ready I'll send it to you for Rocky testing.

**Comment by djhoese** [comment]
@mjkpolo There is a new Geo2Grid tarball for version 1.1 available here:

https://bin.ssec.wisc.edu/pub/davidh/geo2grid-swbundle-20220308-201316.tar.gz

You should be able to treat this like the old version (for the most part), but I'm hoping that it works on Rocky Linux. Thanks and let me know if you have any questions.

**Comment by mjkpolo** [comment]
I might be missing something, but this is what happens when I run `geo2grid.sh`:
[geo2grid.sh.log](https://github.com/ssec/polar2grid/files/8225763/geo2grid.sh.log)
and when I run `pip` I get a similar error:
[pip.log](https://github.com/ssec/polar2grid/files/8225767/pip.log)

**Comment by djhoese** [comment]
You shouldn't use pip at all. The error message you pointed to says it is using `/usr/bin/python3` which is definitely not correct. It is possible something is messed up in the tarball, but I've already had users say they're using this tarball just fine. If it is a problem with the tarball then my guess is that the other users systems don't have a `python3` in `/usr/bin`. That said, the tarball is supposed to force you to use its own internal python.

How did you run this command? You downloaded the tarball, extracted it, but after that did you change any directories? How did you call the geo2grid.sh script? I'll try to reproduce this on my own machine.

**Comment by mjkpolo** [comment]
This is how I did it

```console
[mkurzynski@espresso ~]$ wget https://bin.ssec.wisc.edu/pub/davidh/geo2grid-swbundle-20220308-201316.tar.gz
--2022-03-14 15:44:14--  https://bin.ssec.wisc.edu/pub/davidh/geo2grid-swbundle-20220308-201316.tar.gz
Resolving bin.ssec.wisc.edu (bin.ssec.wisc.edu)... 128.104.108.86
Connecting to bin.ssec.wisc.edu (bin.ssec.wisc.edu)|128.104.108.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1149612512 (1.1G) [application/x-gzip]
Saving to: ‘geo2grid-swbundle-20220308-201316.tar.gz’

geo2grid-swbundle-20220308-201316.t 100%[==================================================================>]   1.07G   387MB/s    in 2.8s

2022-03-14 15:44:17 (387 MB/s) - ‘geo2grid-swbundle-20220308-201316.tar.gz’ saved [1149612512/1149612512]

[mkurzynski@espresso ~]$ tar xf geo2grid-swbundle-20220308-201316.tar.gz
[mkurzynski@espresso ~]$ echo 'export GEO2GRID_HOME=$HOME/geo2grid-swbundle-20220308-201316
> export PATH=$GEO2GRID_HOME/bin:$PATH' >> /home/mkurzynski/.bashrc
[mkurzynski@espresso ~]$ source /home/mkurzynski/.bashrc
[mkurzynski@espresso ~]$ wget https://bin.ssec.wisc.edu/pub/CSPP/hidden/GEO/GEO2GRID/v1_0_2/CSPP_GEO2GRID_V1.0.2_TEST_DATA.tar.gz
--2022-03-14 15:45:31--  https://bin.ssec.wisc.edu/pub/CSPP/hidden/GEO/GEO2GRID/v1_0_2/CSPP_GEO2GRID_V1.0.2_TEST_DATA.tar.gz
Resolving bin.ssec.wisc.edu (bin.ssec.wisc.edu)... 128.104.108.86
Connecting to bin.ssec.wisc.edu (bin.ssec.wisc.edu)|128.104.108.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3995603680 (3.7G) [application/x-gzip]
Saving to: ‘CSPP_GEO2GRID_V1.0.2_TEST_DATA.tar.gz’

CSPP_GEO2GRID_V1.0.2_TEST_DATA.tar. 100%[==================================================================>]   3.72G   368MB/s    in 10s

2022-03-14 15:45:41 (365 MB/s) - ‘CSPP_GEO2GRID_V1.0.2_TEST_DATA.tar.gz’ saved [3995603680/3995603680]

[mkurzynski@espresso ~]$ tar xf CSPP_GEO2GRID_V1.0.2_TEST_DATA.tar.gz
[mkurzynski@espresso ~]$ cd geo2grid_test/abi/
[mkurzynski@espresso abi]$ mkdir work && cd work
[mkurzynski@espresso work]$ geo2grid.sh -r abi_l1b -w geotiff --num-workers 8 --progress  -f ../input
openssl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
/usr/bin/python3: Error while finding module specification for 'polar2grid.glue' (ModuleNotFoundError: No module named 'polar2grid')
```

**Comment by djhoese** [comment]
I just did this and it worked fine:

```bash
[davidh@espresso ~]$ wget https://bin.ssec.wisc.edu/pub/davidh/geo2grid-swbundle-20220308-201316.tar.gz
--2022-03-14 16:06:53--  https://bin.ssec.wisc.edu/pub/davidh/geo2grid-swbundle-20220308-201316.tar.gz
Resolving bin.ssec.wisc.edu (bin.ssec.wisc.edu)... 128.104.108.86
Connecting to bin.ssec.wisc.edu (bin.ssec.wisc.edu)|128.104.108.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1149612512 (1.1G) [application/x-gzip]
Saving to: ‘geo2grid-swbundle-20220308-201316.tar.gz’

geo2grid-swbundle-20220308-201316.tar.gz                                100%[==============================================================================================================================================================================>]   1.07G   324MB/s    in 3.4s    

2022-03-14 16:06:56 (324 MB/s) - ‘geo2grid-swbundle-20220308-201316.tar.gz’ saved [1149612512/1149612512]

[davidh@espresso ~]$ tar xf geo2grid-swbundle-20220308-201316.tar.gz
[davidh@espresso ~]$ ./geo2grid-swbundle-20220308-201316/bin/geo2grid.sh -h
Running one-time initialization of environment...
usage:
    geo2grid.sh -h
...
```

Now we get to track down the differences between your environment and mine.

**Comment by djhoese** [comment]
I see you do:

```bash
export CSPP_GEO_GEOCAT_HOME=$HOME/cspp-geo-geocat-1.0.3b
source $CSPP_GEO_GEOCAT_HOME/geocat_env.sh
```

In your bashrc. I don't have sudo on espresso so I can't see if you have these directories in your home directory. In that case they could be effecting this. Do you have them in there?

**Comment by djhoese** [comment]
Sorry, this looks like it might be a bug in the tarball that is just brought to light by your environment. It's been a while since I've looked at how these scripts load PATH and find python, but they don't seem to do what I expect. I'll have to take a closer look. I'm honestly not sure how it is working at all.

**Comment by djhoese** [comment]
Sorry everyone for all these messages. Inside the `GEO2GRID_HOME/bin/env.sh` script is the line:

```
source $P2G_CONDA_BASE/bin/activate
```

This is supposed to activate the internal conda environment and set up all the correct python locations. For some reason, this isn't running for you.

**Comment by djhoese** [comment]
I talked with @mjkpolo on slack and we confirmed that the old G2G tarball is not Rocky compatible, but the new tarballs (the betas for 1.1 that I've been giving out are compatible). The geotiffs were produced, but due to some legacy code in the compare script in the test data tarball the comparison fails. I'll create another issue for that.

For now, I think this can be closed.
