### ISSUE TITLE
Polar2Grid Versioin 3.0: Help for writer option says user can specify multiple writers in one command

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#415]
The text help for the "Writing" section says this:

Writing:
  -w WRITER, --writer WRITER
                        Writers to save datasets with. Multiple writers can be provided by specifying '-w' multiple times
                        (ex. '-w geotiff -w awips_tiled'). Supported writers: geotiff

We do not wish to support multiple writers for a single p2g invocation at this time.  There are multiple execution options that are not compatible between different options, and this would also require alot of testing.

**Comment by djhoese** [comment]
I can update this, but I just realized do we want to support multiple writers for G2G?
