### ISSUE TITLE
P2G V3.0 files cannot be displayed in AWIPS

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#417]
I am using Polar2Grid Version 3.0 (polar2grid-swbundle-20211219-125805).  I have tried creating AWIPS crefl and I and m-band files using commands like this:

polar2grid.sh -r viirs_sdr -w awips_tiled --num-workers 4 -p i01 -g lcc_conus_300 --sector-id LCC --letters --compress -f

polar2grid.sh -r viirs_sdr -w awips_tiled --awips-true-color --awips-false-color --num-workers 4 -g lcc_conus_300 --sector-id LCC --letters --compress -f

The software successfully executes the commands and creates files, but they cannot be ingested by AWIPS.  I compared the files headers between two of the same tiled NetCDF files, and they are very, very different.  

I am attaching the orignal and new headers dumped from the files, and I put the NetCDF files on bumi at   /data/users/kathys/version_3_0_timing/sample_tiles

The files below are also available at the bumi directory.

[orig_awips.txt](https://github.com/ssec/polar2grid/files/8100278/orig_awips.txt)

[new_awips.txt](https://github.com/ssec/polar2grid/files/8100282/new_awips.txt)

**Comment by kathys** [comment]
I also added and i04 set of files too to the bumi directory also.  Might be better to start with that since it does not require combining with other files like the true and false color crefl files do.

**Comment by kathys** [comment]
Lee Cronce helped me to identify problems in the files. First, he y and x units need to be "meters" instead of "meter".  Next, there is not "units" attribute in the file.  It needs to be "kelvin".

**Comment by djhoese** [comment]
Strange on the meter/meters thing as we've tested these files with GLM and that worked just fine. They are both CF-compatible units so that's annoying on AWIPS's part. As for the units, in the crefl09 you gave me they have `units` equal to `%`. I can double check the BT bands and work on the meter/meters fix.
