### ISSUE TITLE
Ensure all GINA use cases properly execute

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#436]
GINA sent us a list of all the ways they are using Polar2Grid Version 2.3.  We need to make sure these examples work before P2G Version 3.0 is released, and should provide them with the new way these should be executed.

- [x] SCMI product generation
 --sector-id Polar --letters --compress --fix-awips --grid-coverage 0.00001 --output-pattern 'UAF_AII_{satellite}_{instrument}_{product_name}_{sector_id}_{tile_id}_{begin_time:%Y%m%d_%H%M}.nc' 

- [x]  viirs2gtiff.sh --grid-coverage 0.002 -p 'i01 i02 i03 i04 i05' -g polar_300 

- [x] viirs2gtiff.sh --grid-coverage 0.002 --png-quicklook -p  'adaptive_dnb dynamic_dnb histogram_dnb hncc_dnb dnb' -g polar_600

- [x] viirs2gtiff.sh --grid-coverage 0.002 -p 'i01 i02 i04 i05 ' -g polar_300 --dtype real4 --output-pattern {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif

- [x] crefl2gtiff.sh --grid-coverage 0.002 --true-color -g polar_300

- [ ] modis2gtiff.sh --grid-coverage 0.002 -p 'ir31 ir30 bt30 bt31' -g polar_1km --dtype real4 --output-pattern {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif"   

> **_ For this use case in Polar2Grid Version 3.0, Dave found a bug in proj that can affect a very, very small number of gridded output values if there are missing scans in the data segment._**

- [x] crefl2gtiff.sh --grid-coverage 0.002 --true-color -g polar_250

- [x] modis2gtiff.sh --grid-coverage 0.002 -p 'vis01 vis02' -g polar_250

- [x] modis2gtiff.sh --grid-coverage 0.002 -p 'vis01 vis02 vis03 vis04 vis05 vis06 vis07' -g polar_500

- [x] modis2gtiff.sh --png-quicklook --grid-coverage 0.02 -p 'ir30 ir31 bt30 bt31' -g polar_1km

- [x] polar2grid.sh avhrr gtiff -g 203_1k --grid-coverage 0.001 -p 'band3b_bt band4_bt band5_bt' --dtype real4 --output-pattern {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif

- [x] polar2grid.sh avhrr gtiff -g 203_1k --grid-coverage 0.001 -p 'band1_vis band2_vis band3a_vis band3b_bt band4_bt band5_bt'

- [ ] polar2grid.sh amsr2_l1b gtiff --grid-coverage 0.002 -g 203_10km -p 'rgb_color'

> **_Don't have the definition of `rgb_color` to test._**

- [x] polar2grid.sh clavrx gtiff --grid-coverage 0.002 -g alaska_300 -p 'cld_emiss_acha cld_height_acha cld_opd_dcomp cld_reff_dcomp cld_temp_acha cloud_phase cloud_type cld_base_altitude_acha '

- [x] polar2grid.sh clavrx gtiff --grid-coverage 0.002 -g alaska_300 -p 'cld_emiss_acha cld_height_acha cld_opd_dcomp cld_reff_dcomp cld_temp_acha cloud_phase cloud_type cld_base_altitude_acha ccl_layer_flag ccl_1 ccl_2 ccl_3 ccl_4 ccl_5' --dtype real4 --output-pattern {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif

> **_There are some image reprojection artifacts that are removed in v3.0 P2G in the ccl images.  This is true of the 1000m reprojections too._**

- [x] polar2grid.sh clavrx gtiff --grid-coverage 0.002 -g alaska_1000 -p 'cld_emiss_acha cld_height_acha cld_opd_dcomp cld_reff_dcomp cld_temp_acha cloud_phase cloud_type cld_base_altitude_acha '

- [x] polar2grid.sh clavrx gtiff --grid-coverage 0.002 -g alaska_1000 -p 'cld_emiss_acha cld_height_acha cld_opd_dcomp cld_reff_dcomp cld_temp_acha cloud_phase cloud_type cld_base_altitude_acha ccl_layer_flag ccl_1 ccl_2 ccl_3 ccl_4 ccl_5' --dtype real4 --output-pattern {satellite}_{instrument}_{product_name}_{begin_time}_{grid_name}.float.tif

**Comment by djhoese** [comment]
@spruceboy I see "rgb_color" for the `amsr2_l1b` case. Is that a custom composite of some sort?

**Comment by spruceboy** [comment]
I don't think we ever used that, so I can't think of what it would be.  If you need more info I can look at how we have that configured.  We only make a few brightness temperature awips products from the amsr2_l1b, and they do not see much use, mostly folks are using the higher level products.
