### ISSUE TITLE
--colorbar-align in geo2grid documentation

### ISSUE THREAD

**Issue by ScottLindstrom** [ssec/polar2grid#439]
If you specify "--colorbar-align right" but don't also specify --colorbar-vertical, the -align request is ignored.  The choices for align are top, bottom, left, right.  Horizontal or Vertical is implied in those choices.  Can --colorbar-vertical be removed and have everything be controlled by --colorbar-align?

**Comment by djhoese** [comment]
So technically, although maybe not logically, it is possible to have a colorbar be vertical but also be on the bottom. At least in the underlying pycoast code. I think it rarely looks the way people expect though and that's probably why I made the changes to have these combinations ignored but maybe should have raised an error instead. I will double check the logic and can deprecate the `--colorbar-vertical` option. Thanks.
