### ISSUE TITLE
Update compare script in test data tarball to use bundle script

### ISSUE THREAD

**Issue by djhoese** [ssec/polar2grid#455]
As mentioned in #402, the compare script currently fails when run against the new tarball because it tries to use the `python` binary from the main software tarball:

```
./g2g_compare_geotiff.sh: line 67: /home/mkurzynski/geo2grid-swbundle-20220308-201316/bin/python: No such file or directory
```

In the new tarballs the python binary is in a lower-level directory and not available from the `bin` directory. Additionally it follows newer linux practices of calling the python binary `python3`. Most importantly though is that the script in the test tarball is a copy of an older version of the compare script that is in the bundle. This script has seen some major improvements and is always updated to work with the tools installed in the bundle so we should replace it with a call to `POLAR2GRID_HOME/bin/p2g_compare.sh` or whatever way the tests are pointed to the main tarball.

This should be done for P2G and G2G tests.

**Comment by kathys** [comment]
This is done.
