### ISSUE TITLE
Change support for SeaDAS product from HDF4 to NetCDF4 Output Format

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#457]
The original format of the SeaDAS retrievals file was HDF4, but the official format of the data is NetCDF4.  Liam recently updated his SeaDAS version to the latest one available and it by default creates NetCDF4 format.  The only arrays that we care about in these files right now are **chlor-a** and **l2_flags**.  It does not look like anything has changed when going from one format to another as far as data type, valid range, etc. 

I put sample SeaDAS NetCDF files on _bumi:/data/test_data/old_polar2grid_data/modis/seadas/seadas_netcdf_ .  I do not have Aqua MODIS file samples yet since that instrument has not been producing science products since March 31.  It is supposed to producing science products again soon.  When it does, I will get a sample of that too.  Also, Liam is producing these from our antenna on bolt at:  
https://bolt.ssec.wisc.edu/products/jpss/level2/
https://bolt.ssec.wisc.edu/products/eos/level2/

**Comment by djhoese** [comment]
Closed when https://github.com/pytroll/satpy/pull/2209 gets merged.

**Comment by djhoese** [comment]
The PR was merged so this can be closed.
