### ISSUE TITLE
Support new CSPP Active Fire I-Band Format

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#458]
We are working on releasing a new version of the Active Fire software from CSPP.  The I-Band NetCDF4 format has changed, so the P2G Active Fire Reader no longer works on these files.  The good news is that the format is very similar to the M-Band format now, so I am hoping  that you can use the same or very similar code to support it.  I only want to support the NetCDF files and not the .txt files.

The I-Band NetCDF active fire files now contain this array:

  ubyte fire_mask(row, col) ;
  		fire_mask:long_name = "fire mask" ;
  		fire_mask:legend = "Classes: \n  0 missing input data \n  1 bowtie\n  2 unused\n  3 non-fire water \n  4 cloud \n  5 non-fire land \n  6 unknown \n  7 fire (low confidence) \n  8 fire (nominal confidence) \n  9 fire (high confidence)" ;

which is what is used to plot the 7-9 confidences.

I put one S-NPP and one NOAA20 set of output files here:

_bumi:/data/test_data/old_polar2grid_data/cspp_active_fire_version_v2_0/_

We also want to be able to plot the new **ubyte FP_PersistentAnomalyCategory(nfire)**  but I am not sure how to do that yet.  People might want to use it to mask out some of the active fires that have been detected.  I need to talk to other people about it first.

**Comment by djhoese** [comment]
Should be fixed with Satpy PR: https://github.com/pytroll/satpy/pull/2115

**Comment by kathys** [comment]
The fix to support the new file formats does not work for either AFIMG or AFMOD files.  The main error message in the log files says `KeyError: 'sensor'`.  I am using the data described above, and the log file is here:  `bumi:/data/test_data/old_polar2grid_data/cspp_active_fire_version_v2_0/af_images`

I am able to list out the correct products both the AFIMG and AFMOD files using --list-products, but not able to actually created any products.

**Comment by djhoese** [comment]
Looks like I didn't properly test this. I have a fix for the reader portion of it, but it looks like the 1D nature of the data is revealing bugs in other parts. The files in the `snpp_af` directory, what region does it cover? I remapped to "211e" and I'm not sure I'm seeing anything.

**Comment by kathys** [comment]
Here is the region it covers



![Image](https://user-images.githubusercontent.com/1848019/192860202-df4665e9-1c97-42e9-88df-145679894d47.png)

**Comment by djhoese** [comment]
The Satpy PR has been merged so this should be fixed in the next tarball. We'll have to verify the "T" IR band products as they looked a little funny to me. Closing for now. We can reopen if things are still wrong.
