### ISSUE TITLE
ACSPO reader using nearest neighbor resampling for VIIRS and MODIS

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#474]
The Polar2Grid Version 3.0 reader is defaulting to use nearest neighbor resampling for all of the instruments that it supports (MODIS, VIIRS and AVHRR).  For AVHRR, that is fine, but EWA resampling should be used for VIIRS and MODIS.  Dave took a quick look at the ACSPO NetCDF files, and it looks like the problem might be that the global "SENSOR" attribute has the sensor name in  all caps  (ie, VIIRS, MODIS).  

I put some recent NetCDF ACSPO files for MODIS and VIIRS here:

_bumi:/data/users/kathys/test_data/acspo/2022_examples_

**Comment by djhoese** [comment]
This is fixed in Satpy now with https://github.com/pytroll/satpy/pull/2114
