### ISSUE TITLE
add_coastline.sh script not placing labels correctly

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#503]
Using the same `add_coastline.sh`script that I have used in the past on an SST image, results in the colorbar temperature labels being incorrectly displayed.  The range of values that I am using are 275-305K.  The only temperature that is labelled is 275 and it is located in the wrong location along the colorbar. 

The data is located here:  `bumi:/data/users/kathys/test_data/acspo/example_for_documentation/sst_file`

The command I used:
add_coastlines.sh noaa20_viirs_sst_20220810_184327_great_lakes.tif  --add-colorbar --colorbar-text-color="white" --colorbar-units="°K" --colorbar-align bottom --colorbar-title="VIIRS ACSPO SST 10 August 2022 18:43 UTC" --colorbar-text-size 20 --colorbar-height=35

![Image](https://user-images.githubusercontent.com/1848019/186473656-af36d701-4864-44a5-bf36-90b0db09a17e.png)

**Comment by djhoese** [comment]
What are the different files in this directory? What's the difference between `orig` and `rescaled` and `rescaled_wcolor` and `wcolor` and the one with no additional suffix?

**Comment by kathys** [comment]
These are files created as part of the steps involved in the process of creating a color enhanced, customized grid and scaled image for the doc section on ACSPO SSTs.  I did not explain very well about the image I am using to add the colorbar.  The image that I am am applying the add_coastlines.sh to, is the `noaa20_viirs_sst_20220810_184327_great_lakes.tif` which is just a copy of the `noaa20_viirs_sst_20220810_184327_great_lakes_rescaled_wcolor.tif`.  So the image was created using a customized grid and customized scaling with a colortable added.

**Comment by djhoese** [comment]
Should be closed by #507
