### ISSUE TITLE
Request custom products to appear in --list-products results

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#505]
In the current versions of G2G and P2G, if you create a custom product (such as an RGB), it will appear in the `--list-products-all` output as part of the Satpy options that are not explicitly supported in P2G.  These options start with a `*`, and that list can sometimes be very long.  It would be more helpful to the user if their own products would appear in their standard `--list-products` list.

**Comment by djhoese** [comment]
Do you want me to add any "headers" to the `--list-products` output or identify in some way the difference between p2g-builtin products versus custom composites. For example, here is the `--list-products` output for viirs sdr:

```
polar2grid.sh -r viirs_sdr -w geotiff --list-products -f /data/satellite/viirs/conus_day/*t1801*
INFO     : Sorting and reading input files...
INFO     : Loading product metadata from files...
INFO     : Using default product list: ['i01', 'i02', 'i03', 'i04', 'i05', 'm01', 'm02', 'm03', 'm04', 'm05', 'm06', 'm07', 'm08', 'm09', 'm10', 'm11', 'm12', 'm13', 'm14', 'm15', 'm16', 'adaptive_dnb', 'dynamic_dnb', 'hncc_dnb', 'true_color', 'false_color', 'ifog']
adaptive_dnb
dnb_lunar_azimuth_angle
dnb_lunar_zenith_angle
dnb_sat_azimuth_angle
dnb_sat_zenith_angle
dnb_solar_azimuth_angle
dnb_solar_zenith_angle
dynamic_dnb
false_color
histogram_dnb
hncc_dnb
i01
i01_rad
i02
...
```

But the `--list-products-all` shows:

```
polar2grid.sh -r viirs_sdr -w geotiff --list-products-all -f /data/satellite/viirs/conus_day/*t1801*
INFO     : Sorting and reading input files...
INFO     : Loading product metadata from files...
INFO     : Using default product list: ['i01', 'i02', 'i03', 'i04', 'i05', 'm01', 'm02', 'm03', 'm04', 'm05', 'm06', 'm07', 'm08', 'm09', 'm10', 'm11', 'm12', 'm13', 'm14', 'm15', 'm16', 'adaptive_dnb', 'dynamic_dnb', 'hncc_dnb', 'true_color', 'false_color', 'ifog']
### Custom/Satpy Products
*DNB
*ash
*cimss_cloud_type
*cimss_cloud_type_raw
*cloud_phase
*cloud_phase_distinction
...

### Standard Available Polar2Grid Products
adaptive_dnb
dnb_lunar_azimuth_angle
...
```

So you can see the asterisks for the "custom" products as well as the separation by the headers (prefixed with `###`).

**Comment by kathys** [comment]
I think the separation with the #### is good.  I will try to emphasize that in the documentation too.

**Comment by kathys** [comment]
These are good questions.  I like the asterisks on the `--list-products-all` products.  And I think it is also a good idea to put asterisks on the customized products too.  Then it is becomes easy to identify the default products in all situations.
