### ISSUE TITLE
Inconsistent MiRS output product filenames

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#509]
P2G V3 output MiRS GeoTIFF product filenames are inconsistent between satellites.  The output products from metopb are prefixed with `metopb`, while the products from metopc are prefixed `metop-c`.    NOAA19 products have a `noaa-19` prefix, while NOAA20 have a `noaa20` prefix.  I would prefer not to use a hyphen in the satellite name if this is easy to do.   P2G Version 2.3 did not include hyphens in the satellite name.

**Comment by djhoese** [comment]
As discussed in the meeting today, I didn't know metop-c was a thing, that needs to be added to `glue.py` as a renaming of that satellite. noaa-19 is actually an inconsistency between MiRS and VIIRS reader. I will change it to be `noaa19` to be consistent with `noaa20` and others that VIIRS already supports.
