### ISSUE TITLE
CLAVRx resampling defaults need changing

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#518]
In P2G Version 2.3, the CLAVRx resampling was set to EWA 40:1 fornav settings for all instruments, although I see 40:1 and 10:1 in the MODIS files.  Not sure from the log files why that would be the case.  I would like the defaults to be set to whatever they were in Version 2.3.  I see that currently the V3.0 VIIRS settings are using nearest neighbor, which definitely needs to be changed.  I can see the difference in the resolution for the VIIRS products when compared to those created using v2.3.

**Comment by djhoese** [comment]
This is kind of funny to me. The whole reason the `resampling.yaml` was added is that we (you and Liam I think) were "annoyed" that we had to use one set of parameters for all instruments for a particular reader. I can change this, but I'm surprised that CLAVRX MODIS output looks better with 40:1 than it does with 10:1.

Looking at the configuration file it looks like VIIRS is configured specifically for the `viirs_sdr` reader. I should change that to be for all VIIRS data from any reader, at least as a fallback. I will make it so anything from the clavrx reader is 40:1.

**Comment by kathys** [comment]
Understood.  But right now, I am just trying to make sure that the images are at least as good as the originals.  I figure we can worry about tweaking the parameters once we get this release out.  To do a fair comparison of the images, I need to limit the variables so it is easier to track down problems and have a fair sense of timing and resource comparisons.  People use these products.  They will notice differences.  I would not change the capability to change the yaml, but for now, I want  the parameters to be set to the original values.

**Comment by djhoese** [comment]
I realized something that may have been going on here: it looks like I customized clavrx cloud_phase and cloud_type to use nearest because they are category products. I realize now they should maybe use maximum_weight_mode for EWA resampling in the same effort to preserve the individual categories.

**Comment by kathys** [comment]
That certainly would explain the differences.

**Comment by djhoese** [comment]
Just to be sure, we want this to be 40:1 even though we realized later on that 40:2 was needed for some high-latitude data?

**Comment by kathys** [comment]
Yes.  We may change it, but I want to start with the same values that we were using in Version 2.3.
