### ISSUE TITLE
Inconsistent AVHRR output product satellite naming conventions

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#532]
This issue is the same as MiRS issues 509 in that the naming conventions for satellite products in P2G V3.0 include hyphens for `metop-c` and `noaa-18` and `noaa-19` but no hyphen for `metopb`.  This may well be resolved already, but I just want to make sure that it is consistent across all products too, meaning no hyphens.

**Comment by djhoese** [comment]
We need to get you a new tarball this week. This bug is fixed in the same spot the other one is. All shared logic so this shouldn't be a problem any more.

**Comment by djhoese** [comment]
Closing this as fixed...it pains me to keep them open, but we can if it helps you know what is left to test.
