### ISSUE TITLE
Add support for VIIRS JPSS-2 SDR

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#535]
One requirement for P2G Version 3.0 is that it should be prepared to support JPSS-2 VIIRS SDR image creation.  JPSS-2 is scheduled to be launched on November 1, 2022.

I put a sample of 10 granules that we got from NOAA on bumi at: `bumi:/data/users/kathys/test_data/jpss2/trimmed_granules` .  Note that these granules should be tested for the JPSS-2 format interface as opposed to the actual data contained in it.

**Comment by djhoese** [comment]
What happens if you run the data through right now? My guess is the true color doesn't look great, but otherwise I'd hope that the rest of the stuff just works.

**Comment by kathys** [comment]
The teat data is all Fill Values, so it is used just to test the reader interface.  I was able to list out all of the products, but the geotiff reader failed because the Geo data is all fill values too.

**Comment by kathys** [comment]
The error message says `ValueError: No common point in angle computation.`

**Comment by djhoese** [comment]
Ah ok. That means it couldn't generate the boundary polygons. There's probably a series of flags you could specify to make it continue running (skip day/night filtering, skip grid coverage, etc). But yeah I suppose it'll fail during resampling no matter what.

Any idea if/when more realistic test data will be made available?

**Comment by kathys** [comment]
I see some data in another set of tests.  Let me try that.  I thought the most recent would be best, but maybe not.

**Comment by kathys** [comment]
I got some data that at least has some actual values in it.  There is a segment of data within a large, probably orbit of data, that has valid data.  And I copied that segment to: `bumi: /data/users/kathys/test_data/jpss2/trimmed_noaa_sdr`.

The full test data is here:  `bumi:/data/users/kathys/test_data/jpss2/sample_noaa_sdr`

I am able to make geotiff images from that shorter segment that are pretty funky looking from the infrared i and m bands, but not from the visible bands. I put the images that I created here:  `bumi:/data/users/kathys/test_data/jpss2/images`

**Comment by kathys** [comment]
Here is what the I-Band 4 looks like from this test data when I reproject it onto the lcc_fit grid:

![Image](https://user-images.githubusercontent.com/1848019/193916290-8f3c6bf4-c5fc-4444-93b5-516d605be58a.png)

**Comment by djhoese** [comment]
:laughing: Beautiful

**Comment by djhoese** [comment]
As discussed in the meeting today, the files produced for the latest test data are accurate. This tells us that the satellite/platform name handling in the reader is sufficient.

Adam Dybbroe just released a new version of pyspectral which includes the RSRs for JPSS-2 and should work when we start getting more realistic data.

Closing as I don't think there is anything else for us to do.
