### ISSUE TITLE
`--compress` options for HDF5 writer is not working

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#540]
I have been trying to get the different compression options for HDF5 writers to work as described in both the hdf5 writer help text as well as the P2G V3.0 documentation, which are inconsistent.  The `-h` text shows 

`  --compress COMPRESS   File compression algorithm (DEFLATE, LZW, NONE, etc)`

while the doc shows:

`--compress  Possible choices: none, gzip, lzf`

I tried gzip and LZW and they did not make any different in the size of the output files, nor was there any indication in the log file that compression was actually applied.

**Comment by kathys** [comment]
Output files and log file here: `bumi:/data/users/kathys/test_data/modis/aqua_v3_h5`

**Comment by djhoese** [comment]
This was fixed in https://github.com/ssec/polar2grid/pull/513 but isn't in the tarball you have.

**Comment by kathys** [comment]
Sorry about that.  I thought it was brought up before, but doing a quick search, I could not find it.

**Comment by djhoese** [comment]
No problem. I knew it had been brought up because I knew I fixed it and it still took me forever to find it (because I slipped the fix into an unrelated PR). I think we mostly talked about it in person and on slack.
