### ISSUE TITLE
Colored frame around true and false color VIIRS GeoTIFFs

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#556]
Using the most recent P2G tarball from October 25, there are now colored edges framing the true and false color GeoTIFF images.  

You can find output from v2.3 here:  `bumi:/data/users/kathys/version_3_0_timing/output_v2.3/noaa20_viirs_true_color_20220718_191730_wgs84_fit.tif`

and compare to v3.0 here:  `bumi:/data/users/kathys/version_3_0_timing/output_viirs_rc2_v_3_0/noaa20_viirs_true_color_20220718_191730_wgs84_fit.tif`

Not sure this was introduced, but it was also a problem in the October 13 tarball, I just checked.

In addition, there seems to be a problem with the day/night filtering too.  See the image from today below, where the upper right corner should be filtering out  the nighttime scene in all bands that go into the RGB.  My operational processing using P2G V2.3 does not show this.

![Image](https://user-images.githubusercontent.com/1848019/199825997-cbf5eaf6-d512-4d5b-87e8-b4c8627f3a37.png)

**Comment by kathys** [comment]
The above image is from S-NPP.  For comparison:

V2.3 .jpg from puff processing (operational machine):  https://ftp.ssec.wisc.edu/pub/eosdb/npp/viirs/2022_11_03_307_1759/images/npp_viirs_true_color_20221103_175946_wgs84_fit.jpg

v3.0 .jpg from milk (test machine):  https://bin.ssec.wisc.edu/pub/ssec/kathys/npp/viirs/2022_11_03_307_1759/images/npp_viirs_true_color_20221103_175946_wgs84_fit.jpg

**Comment by djhoese** [comment]
Yep seeing it on old data too (this is from 2012):

![image](https://user-images.githubusercontent.com/1828519/199831800-870e1f20-e071-470f-a0d2-b32b53a28f7c.png)

**Comment by djhoese** [comment]
Fixed in latest tarball (from today) and fixed with the above referenced satpy PR.
