### ISSUE TITLE
Problems with handling of VIIRS aggregated files

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#561]
I am running a test parallel processing direct broadcast system that uses the P2G Version 3.0 (Nov. 4 tarball).  I can directly compare the output products that are made from the operational system that uses P2G V2.3.  My parallel system uses aggregated VIIRS granules, which is what Liam prefers.  I am seeing differences in the handling of the aggregated versus non-aggregated granules with P2G V3.0.  Using the aggregated granules, I sometimes see these warning messages in the log files:
`WARNING  : Geolocation data contains invalid bounding values. Computing entire array to get bounds instead.`  
When this warning is present, it takes longer to process data, and it does not handle grid cutouts correctly.  For instance, I create cutouts over the great lakes with each overpass.  For an overpass today (8 November), using the unaggregated granules, P2G V3.0 correctly created 2 cutouts only, because the  data did not cover the entire grid set.  Wheras P2G v3.0 incorrectly identified all 7 great lakes grids to be 100% covered using the aggregated data, and created GeoTIFFs for each grid, even though most are blank images.  

I have the data I am looking at on bumi:

Aggregated:
input:  `/data/users/kathys/test_data/viirs_sdr_day/2022_data`
output: `/data/users/kathys/test_data/viirs_sdr_day/output2`

Unaggregated:
input:  `/data/users/kathys/test_data/viirs_sdr_day/2022_data_puff`
output: `/data/users/kathys/test_data/viirs_sdr_day/output`

**Comment by djhoese** [comment]
I don't have time to dive into this right now, but I'll give my initial thoughts:

As mentioned on slack, that warning refers to trying to create a bounding polygon of the swath data so we can do day/night filtering and grid coverage (how much of the swath overlaps with another polygon of interest). The code providing this polygon logic is not great and is being rewritten in pyresample, but that won't be ready any time soon. It has issues with a couple key parts, but mainly with data that has NaNs in it. If the polygon can't be made for some reason then all the lon/lats are computed and a basic bounding box is computed. This is the reason the processing takes longer when you see this warning.

However, I didn't think this would happen with VIIRS. My best guess is that the aggregated dataset has NaNs that the unaggregated doesn't or that Satpy's `viirs_sdr` reader isn't treating them the same. Either way, I guess I'll just have to do better handling of NaNs.

**Comment by kathys** [comment]
Longitude of -902?

**Comment by djhoese** [comment]
Typo, -92

**Comment by djhoese** [comment]
I took those values to represent a decently large rectangle, but maybe I'm wrong? It'd be interesting to see the grids you were mapping it to and this swath? If you drew a box containing the swath would it overlap with each one of the small sub-grid cutouts?

**Comment by kathys** [comment]
These NaNs must also be a part of the unaggregated data too.  Just not sure how the calculations different between them. I always thought that the aggregated files really were just a set of arrays containing individual granules, and not a real concatenated set of continuous data.

**Comment by kathys** [comment]
It is a large rectangle, but it could certainly be larger.  This is from an 8 granule dataset.  The largest ones we use, from merged data, are 12 granules in size.  

The data overlaps with 2 of the 7 grids that I use for making images of the Great Lakes.

**Comment by kathys** [comment]
`bumi:/data/users/kathys/test_data/viirs_sdr_day/great_lakes_grids.conf`

**Comment by djhoese** [comment]
Here is the same plot for the aggregated data:

![image](https://user-images.githubusercontent.com/1828519/201777131-9b6bedce-9dc6-4aa4-bb42-c7cdc23b7316.png)

I'll have to check the shapes of the data. If it is N scans less data then Satpy may be removing some scans based on the file saying it doesn't have valid scans. If they are the same size...then I'm not sure.

**Comment by djhoese** [comment]
Both datasets (I-band longitudes and latitudes) are 12256 rows of data. This would suggest the aggregation is NaN'ing some of the scans for some reason.

**Comment by kathys** [comment]
I tried creating grids from the aggregated input dataset using P2G V2.3, and I was successful.  It created 2 images from the grids which had more than 10% coverage.

Log file and output data here: `bumi:/data/users/kathys/test_data/viirs_sdr_day/output_v_2_3_agg`

**Comment by djhoese** [comment]
It isn't that I doubt that v2.3 works. I understand that it works and probably works in all of the cases you want it to work in. Right now, I'm trying to find the best balance between performance and accuracy and handling all of the edge cases.

**Comment by djhoese** [comment]
Unless my edited code is changing something, I don't think it was noted here explicitly so I wanted to say that the unaggregated data case seems to work fine as far as creating the 2 output images it is supposed to create. The percentages of the coverage are also close to what v2.3 was producing (mid to upper teens).
