### ISSUE TITLE
Update to VIIRS L1B reader documentation

### ISSUE THREAD

**Issue by RavenV-tiff** [ssec/polar2grid#563]
Hi, I am requesting an update to the documentation for VIIRS L1B reader to list valid file names. I currently get VIIRS L1B data from NASA LANCE NRT and the naming conventions are different from those accepted by P2G. I can rename the files to make P2G recognize the files as valid however, it would be nice to have a list of file names the program is searching for. Either that or perhaps update this function to also accept LANCE VIIRS file names.

Here's an example of a GEO DNB file from LANCE. I'm not sure how to rename this file to a valid name.
VNP03DNB_NRT.A2022315.0612.002.2022315075725.nc

Thanks

**Comment by djhoese** [comment]
It looks like those files are already supported by the Satpy reader ([here](https://github.com/pytroll/satpy/blob/3f53644ac757de846121e3f3c6df24b7c80a18b9/satpy/etc/readers/viirs_l1b.yaml#L39-L42) is the YAML configuration file with the file patterns). This means that these filenames would be supported out of the box in the next Polar2Grid release.

As far as documenting, I'm not sure where we stand on documenting every filenaming scheme that can be provided. For some readers this could get kind of long. @kathys and I will talk about this and see what we think.

**Comment by djhoese** [comment]
I was looking through old issues today and rediscovered this issue. Kathy and I talked and we don't think it is necessary to document every filenaming scheme that might be supported. There are many that are added or changed in Satpy and we would never be able to keep up with those changes. Additionally, we have a tight range of features that we are funded to support so we can't guarantee that something supported in Satpy is also perfectly supported here. There are many undocumented features in Polar2Grid/Geo2Grid and for now they'll have to stay that way. Thanks for understanding.
