### ISSUE TITLE
G2G AGRI reader does not support FY4B

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#564]
I downloaded an FY4B AGRI dataset from CMA today, and I was not able to generate any geotiffs from it using Geo2Grid.  I was able to list out the products.

It looks like this is the problem according to the log file:

AttributeError: 'NoneType' object has no attribute 'ndim'
[2022-11-15 21:58:51,807] : PID  20059 : ERROR    : traceback : exc_handler : 'NoneType' object has no attribute 'ndim'

Dataset:  
`bumi:/data/users/kathys/geo/test_data_geo/agri/0300`
Logfile:
`bumi:/data/users/kathys/geo/agri4b`

I am not sure we should plan to support FY4B right now.  Maybe it would be better for a v1.2 release.

**Comment by djhoese** [comment]
As mentioned a while ago, FY4B has different bands to FY4A AGRI. To properly support it required some major gymnastics in Satpy's readers, but luckily @simonrp84 did that as part of https://github.com/pytroll/satpy/pull/2125
