### ISSUE TITLE
Geo2Grid Release 1.1 Colorbar Issues

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#594]
Greetings!   We have a few Geo2Grid 1.1 colorbar-related questions/issues:
1.)  1.1 documentation (add_coastlines.sh, colorbar) says that   --colorbar-minor-tick-marks   is a valid option, but add_coastlines.sh breaks if I try to use this option  ("add_coastlines.py: error: unrecognized arguments: --colorbar-minor-tick-marks 100").
2.)   Related to #1 above -- When analyzing cloudtop height (HT) and cloudtop temperature (TEMP) Level-2 GOES imagery, it would be nice to have the   --colorbar-minor-tick-marks   option available to us!   According to the 1.1 doc, the default for this option is 1.0.  Interestingly, when displaying a colorbar with cloudtop temperature (TEMP) with "--colorbar-tick-marks 10", we end up with minor tick marks plotted every 0.5 K.  FYI, in this case the range of TEMPs is approximately 200K -> 300K, and the image frame is 2000 pixels wide and 1500 pixels tall.
3.)   Perhaps related to issue #587 (Scott Lindstrom) -- colorbar numbers plotted on a right-aligned colorbar are displayed in the opposite sense compared with colorbar numbers plotted on a bottom-aligned colorbar.

**Comment by djhoese** [comment]
>  1.1 documentation

Which documentation are you reading? The website or the PDF? The minor ticks flag was added just after the 1.1 release after @ScottLindstrom pointed out the need for it in #573. It seems like the PDF doesn't have this documented but the website does. The website must have been generated and uploaded after the addition of the flag.

And yes, your number 3 is exactly #587 and will be fixed in a future version.

**Comment by jpnIII** [comment]
Thank you, Dave!

I was looking at the 1.1 website.   Is there another G2G version beyond 1.1 that I need to get that has the minor ticks flag option enabled?  I got the error message when running 1.1

Thank you very much for fixing #587, Dave.

**Comment by djhoese** [comment]
There is no public release that includes it and the fixes for some of the recent colorbar/colormap issues discovered by Scott haven't been merged and released in the upstream packages that Geo2Grid depends on. Kathy and I are currently finishing up a Polar2Grid 3.0 release. When that is done we could put a G2G 1.1.1 on our TODO list but at this point I have no timeline for that.

**Comment by jpnIII** [comment]
Understood.   Good luck on the Polar2Grid 3.0 release!

**Comment by djhoese** [comment]
I don't think we ever released a 1.1.1 but at this point we are pretty feature-complete on a G2G 1.2 release and it includes fixes for the issues you've identified here. Closing this for that reason.

**Comment by jpnIII** [comment]
Thank you Dave et al. !

Sincerely,

Jim
