### ISSUE TITLE
Any plans for Meteosat Third Generation (MTG) imagery via Geo2Grid?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#611]
Hi all -- Just a question -- As you know, Meteosat Third Generation (MTG) just released their initial image (https://www.eumetsat.int/features/discover-first-images-mtg-i1).  According to the following Twitter link (https://twitter.com/PyTrollOrg/status/1654033745555406851), this beautiful True-color, etc. imagery was generated using Satpy.  Congratulations are in order!   Apparently MTG is due to start dissemination of operational imagery late in 2023 -- December perhaps?   However, SSEC/CIMSS will likely have access to some MTG imagery even before December 2023, but there are no specifics, yet.  

Are there any plans to release a version of Geo2Grid that will have MTG display capabilities?  

Thank you!

Sincerely,

Jim

**Comment by djhoese** [comment]
Unofficial support is probably available already using the `fci_l1c_nc` reader name. No testing has been done and I'd have to check with @kathys if we have any funding to try to support it. If I remember correctly our primary funding does not include non-US instruments.

**Comment by djhoese** [comment]
Oh I should add that I know EUMETSAT did some last minute changes to Satpy in their own local copies to generate the true color they did. These changes are not in Satpy...yet.

**Comment by djhoese** [comment]
I'm going to close this for now. As mentioned the readers from Satpy are available (but maybe not all custom compression plugins/dependencies to read some file formats), but official support will require direct (or broad?) funding.
