### ISSUE TITLE
Create new Polar2Grid Reader for CSPP VIIRS Land Surface Temperature EDR

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#619]
Please add a reader in support the CSPP VIIRS Land Surface Temperature Product.  This should be very similar to if not identical to the CSPP Geo2Grid reader being added:  https://github.com/ssec/polar2grid/issues/613

File prefix:  `LST_*.nc`

Array:  `short VLST`

units:  `Kelvin`

Scale Factor:  `float LST_ScaleFact` which is .005
Offset:  `float LST_Offset` which is 200.

This will have to support a huge range of temperatures.  We will have to work on the best color table with the GEO team too.  The valid  range is 213 to 343 K. 

Test data can be found here:
         `bumi:/data/users/kathys/test_data/viirs_edr/j01/asci`
         `bumi:/data/users/kathys/test_data/viirs_edr/npp/asci`

**Comment by djhoese** [comment]
I don't see any "LST_*" files in the `asci` directory. Copy/paste error on the directory?

**Comment by kathys** [comment]
Looks like I was not successful in getting ASCI files for npp, but the j01 files are there.  The LST software version is 2.0.  For instance:  

_LST_v2r0_j01_s202306081924176_e202306081925403_c202306082036337.nc_

**Comment by kathys** [comment]
I just copied some LST files for npp to the asci test file directory, although they will not match the date/time of the other products that are there.

**Comment by djhoese** [comment]
Ugh these files are different than the others. They aren't even semi-standard NetCDF files with a `scale_factor` and `add_offset`. Instead they have separate scalar variables:

```
        short VLST(Rows, Columns) ;
                VLST:_FillValue = -32768s ;
                VLST:coordinates = "Longitude Latitude" ;
                VLST:long_name = "VIIRS Land Surface Temperature (LST = LST data * LST_ScaleFact + LST_Offset)" ;
                VLST:units = "Kelvin" ;
        float LST_Offset ;
                LST_Offset:long_name = "VIIRS LST Offset" ;
                LST_Offset:units = "1" ;
        float LST_ScaleFact ;
                LST_ScaleFact:long_name = "VIIRS LST Scale Factor" ;
                LST_ScaleFact:units = "1" ;
```

Why?!?!?!

**Comment by djhoese** [comment]
...and it's called "VLST" because it is "VIIRS Land Surface Temperature"? :man_facepalming:

**Comment by djhoese** [comment]
The initial version of this has been added now. Any future issues or changes will be in other issues or pull requests.
