### ISSUE TITLE
Create new Polar2Grid reader for CSPP VIIRS Cloud Product EDRs

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#620]
Please create a reader in support of the CSPP VIIRS Cloud products created from the CSPP ASCI EDR software.

File pattern:  `JRR-CloudHeight*.nc`

File Arrays:  `float CldTopTemp` ,  `float CldTopHght`

Temperature unit is Kelvin, Height unit is Meter

I was hoping that these products would have the same format as the GEO product files, but they do not seem to.  However, the color tables and valid ranges should be the same in the end.  

Temperature range:  `180. to 340.`

Height range:  `0.0 to 20000`

Test data:  `bumi:/data/users/kathys/test_data/viirs_edr/j01/asci`
                   `bumi:/data/users/kathys/test_data/viirs_edr/npp/asci`

**Comment by djhoese** [comment]
Any preference on the name of the products when they are loaded via Polar2Grid? CTH/CTT? cloud_top_height/cloud_top_temperature? Or I can match the exact variable naming in the files.

**Comment by kathys** [comment]
Do you and/or Satpy have a preference?  Maybe matching the variable names makes the most sense.  Cannot remember what did we do for MiRS?  I think we matched the variable names.

**Comment by djhoese** [comment]
The initial version of this has been added now. Any future issues or changes will be in other issues or pull requests.
