### ISSUE TITLE
Add support for MiRS NOAA-21 ATMS products

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#665]
We have a new version of the MiRS software that is about to be released as part of CSPP LEO.  It adds support for NOAA-21 ATMS.  The new software is v11r9.  P2G v3.0 creates good SNPP and NOAA-20 MiRS images from this new output, but it fails when trying to create NOAA-21 images.  

I know we do not have any limb corrections yet for the NOAA-21 ATMS individual bands, but P2G v3.0 also fails when trying to produce non-brightness temperature images too, such as `rain_rate`, `sea_ice` and `tpw`. 

Sample data `bumi:/data/users/kathys/test_data/mirs/2023_examples`

Log files: 
`bumi:/data/users/kathys/test_data/mirs/noaa21/mirs_noaa21_band_geotiff_20231009_175328.log`
`bumi:/data/users/kathys/test_data/mirs/noaa21/mirs_noaa21_product_geotiff_20231009_175328.log`

**Comment by djhoese** [comment]
It should be a "simple" update of these two python dictionaries:

https://github.com/pytroll/satpy/blob/fbe017c55c207bfba73a7d4b10491230f8edcaf4/satpy/readers/mirs.py#L50-L80

Looks like I'll need to double check consistency though as it looks like I have entries to handle filenames having "jpss" in them as well as "n20" and "npp". I'm surprised it isn't "jpssN" for 1, 2, etc.
