### ISSUE TITLE
NOAA21 limb correction coefficients for MiRS ATMS images

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#669]
@djhoese   Until we get NOAA-21 ATMS limb correction coefficients to create MiRS Brightness Temperature images, please use the NOAA-20 coefficients that we just received from NOAA.  I will make it clear the documentation that this is the case.

**Comment by djhoese** [comment]
Do you have some NOAA-21 MiRS output that I can test with?

**Comment by kathys** [comment]
Yes.  `bumi:/data/users/kathys/test_data/mirs/2023_examples/noaa21`
