### ISSUE TITLE
Undefined alias 'inversefun' error?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#677]
Greetings, all -- I am using Geo2Grid version 1.2.b, and have been working on incorporating some custom CIMSS, etc. Geo2Grid products that have been defined in the past, but are not currently included in Geo2Grid version 1.2.b.   I realize that Geo2Grid changes from version to version, meaning a product in one version conceivably might not work in a subsequent version, or more likely may need to be tweaked a bit to run in a subsequent version.  I debated whether to send this email, since this is not a huge deal, but I thought that something obvious might stick out to you, without taking too much of your time.  

1.)  At any rate, I tried to run the following  1.2.b  geo2grid.sh command, that failed.  The product was called "plume":

export PYTROLL_CHUNK_SIZE="4096" ; time  geo2grid.sh -r abi_l1b -w geotiff -p plume -g eastern_us --grid-configs geo2grid_config.yaml -f /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C01_G16_s20233630101171_e20233630103546_c20233630103587.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C02_G16_s20233630101171_e20233630103544_c20233630103580.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C03_G16_s20233630101171_e20233630103544_c20233630104057.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C04_G16_s20233630101171_e20233630103544_c20233630103575.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C05_G16_s20233630101171_e20233630103544_c20233630104015.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C06_G16_s20233630101171_e20233630103550_c20233630103593.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C07_G16_s20233630101171_e20233630103557_c20233630104004.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C08_G16_s20233630101171_e20233630103544_c20233630104038.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C09_G16_s20233630101171_e20233630103550_c20233630104041.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C10_G16_s20233630101171_e20233630103557_c20233630104000.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C11_G16_s20233630101171_e20233630103544_c20233630104046.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C12_G16_s20233630101171_e20233630103550_c20233630104009.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C13_G16_s20233630101171_e20233630103556_c20233630104052.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C14_G16_s20233630101171_e20233630103544_c20233630104023.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C15_G16_s20233630101171_e20233630103550_c20233630104034.nc /arcdata/goes/grb/goes16/2023/2023_12_29_363/abi/L1b/RadC/OR_ABI-L1b-RadC-M6C16_G16_s20233630101171_e20233630103557_c20233630104030.nc --output-filename GOES-16_ABI_RadC_plume_2023363_010117Z.tif --num-workers 4

2.)  Here is the end of the error trace.   I can include more output if you wish.

File "/home/shared/bin/geo2grid_v_1_2_b/geo2grid-swbundle-20231006-171312/libexec/python_runtime/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shared/bin/geo2grid_v_1_2_b/geo2grid-swbundle-20231006-171312/libexec/python_runtime/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shared/bin/geo2grid_v_1_2_b/geo2grid-swbundle-20231006-171312/libexec/python_runtime/lib/python3.11/site-packages/yaml/composer.py", line 68, in compose_node
    raise ComposerError(None, None, "found undefined alias %r" 
yaml.composer.ComposerError: found undefined alias 'inversefun'
  in "/home/shared/bin/geo2grid_v_1_2_b/geo2grid-swbundle-20231006-171312/etc/polar2grid/enhancements/generic.yaml", line 1258, column 15

3.)  Following are the lines from my (modified) version of  /home/shared/bin/geo2grid_v_1_2_b/geo2grid-swbundle-20231006-171312/etc/polar2grid/enhancements/generic.yaml.   Note the occurrence of  *inversefun  on line #1258 that caused the problems:

  ir_overview_default:
    standard_name: ir_overview
    operations:
    - name: inverse
      method: *inversefun 
      args: [true]
    - name: stretch
      method: !!python/name:satpy.enhancements.stretch
      kwargs:
        stretch: histogram

4.)  There were actually several different products in my enhancements/generic.yaml  file that had the  *inversefun  in them.  They were all products that had been added to the core generic.yaml file -- they were not core products.  I had to comment-out all of them before I could get the "plume" product to finally work.  Like I said above, a number of the products I am trying to incorporate are old.  Without digging further, I do not know if the  "*inversefun" -related products are even from CIMSS!  Perhaps they are no longer legitimate Geo2Grid products?  I don't know.

5.)  Any suggestion(s) to perhaps fix the  *inversefun  products?  If nothing is obvious here, please don't sweat it.   I DO have 1.2.b working now, with many of the products I added appearing to be viable.   I just had to disable those funky  *inversefun  products first.

Thank you for your help, again!!!

Sincerely,

Jim

**Comment by djhoese** [comment]
Replace:

```
method: *inversefun
```

With:

```
method: !!python/name:satpy.enhancements.invert
```

The `*` syntax is a special YAML syntax where you can define an "alias" somewhere near the top of a YAML file and then reuse that alias throughout the rest of that (single) file. This technically saves you typing, but comes at the cost of not being able to copy/paste YAML that includes aliases to another file without also including the part of the YAML that defines those aliases. Satpy has stopped using these internally for this reason as it causes a lot of confusion and saves us a very small amount of typing.

**Comment by jpnIII** [comment]
Ahh – Thank you, Dave – Later!

Sincerely,

Jim

**Comment by jpnIII** [comment]
Hi again, Dave – Your suggestion appears to have worked.    Thank  you!

Sincerely,

Jim
