### ISSUE TITLE
Recurring problem seen when executing version 1.0 of:    cspp-geo-gglm.sh   on GOES-18 GLM data?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#682]
Hi all -- I am not sure where this note should be sent, so I am trying this avenue...

For quite a while now (a number of months), I have seen an error pop up from time to time when processing GOES-18 GLM data via the 1.0 release of cspp-geo-gglm.sh.   FYI, I have been running cspp-geo-gglm.sh on GOES-18 GLM data since January 2023.  If I recall correctly, this error was much more rare back in 2023.   In the last couple of months, however, the error has been popping up numerous times each day.  The error does not occur when processing GOES-16 GLM  data.

If you look below, you will see some output from processing GOES-18 data from 18Feb2024.  The first chunk of output shows "good" processing when processing the 1309 UTC imagery.   At the bottom, you will see some error output that occurred when  processing the 1310 UTC imagery.

Fortunately, the vast majority of the time cspp-geo-gglm.sh still works correctly.

Thank you for your help with this one!

Sincerely,

Jim
-------------------------------------------------------------------------------------------------------------------------------------------------
(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1255) ATTEMPT TO PROCESS GLM DATA for satellite = GOES-18, sector = full, ccyyddd = 2024049, hhmm = 1309 UTC at:  Sun Feb 18 15:04:31 UTC 2024

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1343) final_src_directory = /arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309*

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1385) 3 GLM LCFA file(s) will be processed in the upcoming  cspp-geo-gglm.sh  command.

(build_goes_abi_2km_grids_of_glm_data3.scr)  (See script line # 1407) (At Sun Feb 18 15:04:31 UTC 2024 Execute:  /home/shared/bin/cspp-geo-gridded-glm-1.0/bin/cspp-geo-gglm.sh --goes-sector full  /arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309000_e20240491309200_c20240491309210.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309200_e20240491309400_c20240491309414.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309400_e20240491310000_c20240491310010.nc

(build_goes_abi_2km_grids_of_glm_data3.scr)  (See script line # 1542) (At Sun Feb 18 15:04:54 UTC 2024 Execute:  mkdir -pv /reimaginator/data/apollo/awg_imagery/glm/LCFA/goes18/2024/2024049/full

(build_goes_abi_2km_grids_of_glm_data3.scr)  (See script line # 1562) (At Sun Feb 18 15:04:54 UTC 2024 Execute:  cp -pv CG_GLM-L2-GLMF-*_G18_s20240491309*.nc /reimaginator/data/apollo/awg_imagery/glm/LCFA/goes18/2024/2024049/full/.

'CG_GLM-L2-GLMF-M3_G18_s20240491309000_e20240491310000_c20240491504320.nc' -> '/reimaginator/data/apollo/awg_imagery/glm/LCFA/goes18/2024/2024049/full/./CG_GLM-L2-GLMF-M3_G18_s20240491309000_e20240491310000_c20240491504320.nc'

(build_goes_abi_2km_grids_of_glm_data3.scr)  (See script line # 1589) (At Sun Feb 18 15:04:54 UTC 2024 Execute:  rm -fv CG_GLM-L2-GLMF-*_G18_s20240491309*.nc

removed 'CG_GLM-L2-GLMF-M3_G18_s20240491309000_e20240491310000_c20240491504320.nc'

------------------------------------------------------------------------------------------------------------------------------------------------
(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1255) ATTEMPT TO PROCESS GLM DATA for satellite = GOES-18, sector = full, ccyyddd = 2024049, hhmm = 1310 UTC at:  Sun Feb 18 15:04:54 UTC 2024

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1343) final_src_directory = /arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310*

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1385) 3 GLM LCFA file(s) will be processed in the upcoming  cspp-geo-gglm.sh  command.

(build_goes_abi_2km_grids_of_glm_data3.scr)  (See script line # 1407) (At Sun Feb 18 15:04:54 UTC 2024 Execute:  /home/shared/bin/cspp-geo-gridded-glm-1.0/bin/cspp-geo-gglm.sh --goes-sector full  /arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310000_e20240491310200_c20240491310207.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310200_e20240491310400_c20240491310408.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310400_e20240491311000_c20240491311008.nc

ERROR:__main__:'NoneType' object has no attribute 'groups'
ERROR:__main__:Gridding minute 2024-02-18 13:10:00 failed.

**Comment by djhoese** [comment]
Please post this to one of the contact methods for the Gridded GLM project:

https://www.ssec.wisc.edu/contact-form/?contact-name=CSPP%20Geo%20Questions

Or the forums:

https://forums.ssec.wisc.edu/viewforum.php?f=74&sid=02d4780493e2c4290b56d208a61e3a99

The official project documentation/PDF may mention other support avenues.
