### ISSUE TITLE
ERROR MSG:  FileNotFoundError: [Errno 2] No such file or directory: '/scratch/gops/cimss_true_color_imagery/abi_l1b_geotiff_fail.log'

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#698]
Hi all -- Hopefully this one will not be too difficult -- I am getting the following error dump when trying to generate a Geo2Grid  cimss_true_color product.   The same error has occurred the last couple of days (the job only gets run 1 time per day).  Interestingly, when I rerun the job later using imagery on  /arcdata  rather than  /satbuf3_data, things work correctly.    FYI, /satbuf3_data is an NFS mount to satbuf3.ssec.wisc.edu.

Thank you for your help!

Sincerely,

Jim

(make_geo2grid_files_with_paramfile16.scr) (See script line # 6973) (At Tue Jun 18 17:10:23 UTC 2024) Execute:  export DASK_ARRAY_CHUNK_SIZE="16777216" ; time geo2grid.sh -r abi_l1b -w geotiff -p cimss_true_color -g MIN --match-resolution -f /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C01_G16_s20241701700215_e20241701709523_c20241701709573.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C02_G16_s20241701700215_e20241701709523_c20241701709565.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C03_G16_s20241701700215_e20241701709523_c20241701709584.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C04_G16_s20241701700215_e20241701709523_c20241701709559.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C05_G16_s20241701700215_e20241701709523_c20241701709569.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C06_G16_s20241701700215_e20241701709529_c20241701709552.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C07_G16_s20241701700215_e20241701709535_c20241701709580.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C08_G16_s20241701700215_e20241701709523_c20241701709576.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C09_G16_s20241701700215_e20241701709529_c20241701709565.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C10_G16_s20241701700215_e20241701709535_c20241701709557.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C11_G16_s20241701700215_e20241701709523_c20241701709569.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C12_G16_s20241701700215_e20241701709529_c20241701709573.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C13_G16_s20241701700215_e20241701709535_c20241701709580.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C14_G16_s20241701700215_e20241701709523_c20241701709584.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C15_G16_s20241701700215_e20241701709529_c20241701709588.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C16_G16_s20241701700215_e20241701709535_c20241701709576.nc --radius-of-influence 50000 --output-filename GOES-16_ABI_RadF_cimss_true_color_2024170_170021Z_nobasemap.tif --num-workers 10 -vvvv

DEBUG    : Starting script with arguments: -r abi_l1b -w geotiff -p cimss_true_color -g MIN --match-resolution -f /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C01_G16_s20241701700215_e20241701709523_c20241701709573.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C02_G16_s20241701700215_e20241701709523_c20241701709565.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C03_G16_s20241701700215_e20241701709523_c20241701709584.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C04_G16_s20241701700215_e20241701709523_c20241701709559.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C05_G16_s20241701700215_e20241701709523_c20241701709569.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C06_G16_s20241701700215_e20241701709529_c20241701709552.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C07_G16_s20241701700215_e20241701709535_c20241701709580.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C08_G16_s20241701700215_e20241701709523_c20241701709576.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C09_G16_s20241701700215_e20241701709529_c20241701709565.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C10_G16_s20241701700215_e20241701709535_c20241701709557.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C11_G16_s20241701700215_e20241701709523_c20241701709569.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C12_G16_s20241701700215_e20241701709529_c20241701709573.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C13_G16_s20241701700215_e20241701709535_c20241701709580.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C14_G16_s20241701700215_e20241701709523_c20241701709584.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C15_G16_s20241701700215_e20241701709529_c20241701709588.nc /satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C16_G16_s20241701700215_e20241701709535_c20241701709576.nc --radius-of-influence 50000 --output-filename GOES-16_ABI_RadF_cimss_true_color_2024170_170021Z_nobasemap.tif --num-workers 10 -vvvv -vv
INFO     : Sorting and reading input files...
DEBUG    : Setting preferred chunk size to 1356 pixels or 14MiB
DEBUG    : Reading ('/home/shared/bin/geo2grid_v_1_2/libexec/python_runtime/lib/python3.11/site-packages/satpy/etc/readers/abi_l1b.yaml',)
DEBUG    : Assigning to abi_l1b: ['/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C01_G16_s20241701700215_e20241701709523_c20241701709573.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C02_G16_s20241701700215_e20241701709523_c20241701709565.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C03_G16_s20241701700215_e20241701709523_c20241701709584.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C04_G16_s20241701700215_e20241701709523_c20241701709559.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C05_G16_s20241701700215_e20241701709523_c20241701709569.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C06_G16_s20241701700215_e20241701709529_c20241701709552.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C07_G16_s20241701700215_e20241701709535_c20241701709580.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C08_G16_s20241701700215_e20241701709523_c20241701709576.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C09_G16_s20241701700215_e20241701709529_c20241701709565.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C10_G16_s20241701700215_e20241701709535_c20241701709557.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C11_G16_s20241701700215_e20241701709523_c20241701709569.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C12_G16_s20241701700215_e20241701709529_c20241701709573.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C13_G16_s20241701700215_e20241701709535_c20241701709580.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C14_G16_s20241701700215_e20241701709523_c20241701709584.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C15_G16_s20241701700215_e20241701709529_c20241701709588.nc', '/satbuf3_data/goes/grb/goes16/2024/2024_06_18_170/abi/L1b/RadF/OR_ABI-L1b-RadF-M6C16_G16_s20241701700215_e20241701709535_c20241701709576.nc']
ERROR    : Unexpected error. Enable debug messages (-vvv) or see log file for details.
DEBUG    : Unexpected error exception: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/shared/bin/geo2grid_v_1_2/libexec/python_runtime/lib/python3.11/site-packages/polar2grid/glue.py", line 499, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/shared/bin/geo2grid_v_1_2/libexec/python_runtime/lib/python3.11/site-packages/polar2grid/glue.py", line 283, in main
    ret = processor()
          ^^^^^^^^^^^
  File "/home/shared/bin/geo2grid_v_1_2/libexec/python_runtime/lib/python3.11/site-packages/polar2grid/glue.py", line 337, in __call__
    return self._run_processing()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shared/bin/geo2grid_v_1_2/libexec/python_runtime/lib/python3.11/site-packages/polar2grid/glue.py", line 350, in _run_processing
    rename_log_file(self.glue_name + stime.strftime("_%Y%m%d_%H%M%S.log"))
  File "/home/shared/bin/geo2grid_v_1_2/libexec/python_runtime/lib/python3.11/site-packages/polar2grid/core/script_utils.py", line 154, in rename_log_file
    with open(fn, "r") as old_file:
         ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/gops/cimss_true_color_imagery/abi_l1b_geotiff_fail.log'

real    0m01.55s
user    0m00.94s
sys     0m00.21s

**Comment by djhoese** [comment]
The last time I've seen this happen was when Geo2Grid was run at the same time in the same directory. Two or more instances running at the same time can conflict with each other. The log file generated initially is named `abi_l1b_geotiff_fail.log`, but after the data is successfully loaded from the input files we take the data start time and rename the log file with that start time. If one instance renames the files and then the other instances goes to rename it just a little bit later, it will fail as yours has.

**Comment by djhoese** [comment]
If this isn't your situation then I will try to figure out what else might be going on.

**Comment by jpnIII** [comment]
Thank you, Dave – I think you nailed it.   Yes, there are indeed two simultaneous Geo2Grid jobs running at the same time, in the same directory!   I am going to start doing the processing in two separate directories, which I suspect will
fix the problem.

Take care!

Sincerely,

Jim
