### ISSUE TITLE
Default daytime band products should be reflectances

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#707]
Our boss Liam has requested that Polar2Grid create actual reflectances that include division by the cosine of the solar zenith angle for each of the polar orbiting satellites that we support, including AVHRR and MODIS.  This should be the default daytime reflectance band output.

**Comment by djhoese** [comment]
What about geo2grid readers?

**Comment by kathys** [comment]
I will speak to Graeme about the defaults for G2G.

**Comment by kathys** [comment]
I understand why you would say this.  I think it will also add processing time too.  But I think it is  the right thing to do, and Liam is right in that our users, especially in the polar regions, will get uniform images across sensors. An important part of this change will be to make sure that I document it well for end users.

**Comment by djhoese** [comment]
Any idea if there are any readers (AVHRR?) where we don't have access to solar zenith angles and they would have to be computed on-the-fly from the lon/lats? That would take the processing time hit from insignificant to extremely annoying.

**Comment by djhoese** [comment]
Just to have it written down for future reference, the readers affected by this are:

* viirs_sdr
* viirs_l1b
* modis_l1b
* mersi2_l1b
* avhrr_l1b_aapp

Any others? Did we ask Graeme about Geo2Grid?

**Comment by djhoese** [comment]
I should note that for readers/files where SZA is not available at every resolution, there will be a required resampling step that will now take longer because of needing to resample not just band data but also the SZA. One example is mersi2 where SZA is available at 1km but some bands are available at 250.

**Comment by kathys** [comment]
Understood.

**Comment by djhoese** [comment]
@kathys I have this functionality, at least the initial draft, implemented in #714. I know you're busy so you probably don't have time to test it but I'm wondering if Liam wants to? If neither of you have time then I might wait to merge the pull request in case other stuff comes up that we want to implement as part of it. Or I could merge it and get you a tarball just to have it when either of you is ready.

**Comment by kathys** [comment]
Thanks very much Dave.  Please provide a tarball.  Liam might want to start testing/using it right away.
