### ISSUE TITLE
Possible problem with version 1.0 of cspp-geo-gglm.sh when processing GOES-18 GLM data?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#720]
Greetings, all -- I just wanted to bring the following to your attention.  FYI, this same problem was discussed in an email sent to both Nick Bearson and the CSPP Geo Issues Group back on 20Feb2024.   I have included that email at the end of this issue report.

For the last several years, I have been routinely running cspp-geo-gglm.sh via cron to generate minute-by-minute, Geo2Grid-compatible GLM files (see  https://cimss.ssec.wisc.edu/csppgeo/gridded-glm.html).   Each output GLM file is a combination of three  20-second GLM files from a given minute (mm00, mm20 and mm40).  In the last week or two, the following error situation has cropped up numerous times, typically involving GOES-18 GLM data ("ERROR:__main__:'NoneType' object has no attribute 'groups'").   I am not sure if Dr. Rudlosky (NOAA/NESDIS/STAR) should be notified of this problem, or not.  I will leave that up to you. 

Thank you for your help!

Sincerely,

Jim

(build_goes_abi_2km_grids_of_glm_data3.scr)  (See script line # 1407) (At Thu Nov  7 16:20:22 UTC 2024 Execute:  /home/shared/bin/cspp-geo-gridded-glm-1.0/bin/cspp-geo-gglm.sh --goes-sector full  /arcdata/goes_restricted/grb/goes18/2024/2024_11_07_312/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20243121456000_e20243121456200_c20243121456209.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_11_07_312/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20243121456200_e20243121456400_c20243121456410.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_11_07_312/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20243121456400_e20243121457000_c20243121457009.nc

ERROR:__main__:'NoneType' object has no attribute 'groups'
ERROR:__main__:Gridding minute 2024-11-07 14:56:00 failed.
--------------------------------------------------------------------------------------------------------------------------------------
The following is an email chain that was sent at 11:08AM CST on Feb 20, 2024 to Nick Bearson and the CSPP Geo Issues Group:

Thank you for checking, Nick!

I’ll be looking forward to hearing what you find!

Sincerely,

Jim

From: Nick Bearson <[nick.bearson@ssec.wisc.edu](mailto:nick.bearson@ssec.wisc.edu)> 
Sent: Tuesday, February 20, 2024 10:20 AM
To: James P. Nelson <[jim.nelson@ssec.wisc.edu](mailto:jim.nelson@ssec.wisc.edu)>; CSPP Geo Issues group <[csppgeo.issues@ssec.wisc.edu](mailto:csppgeo.issues@ssec.wisc.edu)>
Subject: Re: Problem wcspp-geo-gglm.sh and G18 GLM data

Hi Jim,

Thanks for reporting this. I see the same error when I try to process those files myself. If you run the command with the verbose option turned up (-vvv) you’ll see a bit more information about what’s going on. It points me to:

https://github.com/deeplycloudy/glmtools/blob/33490be8df01622f950733faa77998da43f47b0a/glmtools/io/traversal.py#L335

Unfortunately, it’s not immediately clear to me whether this is an issue in the data or glmtools (or the way we’re using glmtools). When I get a chance to do more investigating I’ll let you know what I find.

-Nick

From: James P Nelson III <[jim.nelson@ssec.wisc.edu](mailto:jim.nelson@ssec.wisc.edu)>
Date: Monday, February 19, 2024 at 10:39 PM
To: CSPP Geo Issues group <[csppgeo.issues@ssec.wisc.edu](mailto:csppgeo.issues@ssec.wisc.edu)>
Subject: Problem wcspp-geo-gglm.sh and G18 GLM data
-------------------------------------------------------------------------------
Email sent via SSEC Contact Form
To: [csppgeo.issues@ssec.wisc.edu](mailto:csppgeo.issues@ssec.wisc.edu)
Sent by: James P Nelson III
Email address of sender: [jim.nelson@ssec.wisc.edu](mailto:jim.nelson@ssec.wisc.edu)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/120.0.0.0 Safari/537.36
-------------------------------------------------------------------------------

Hi all -- I was advised by Dave Hoese (SSEC) to submit this note here.   So here
goes...

For quite a while now (a number of months), I have seen an error pop up from
time to time when processing GOES-18 GLM data via the 1.0 release of
cspp-geo-gglm.sh.  (FYI, I have been running cspp-geo-gglm.sh on GOES-18 GLM
data since January 2023.) If I recall correctly, this error was much more rare
back in 2023. In the last couple of months, however, the error has been popping
up numerous times each day. The error does not occur when processing GOES-16 GLM
data.

If you look below, you will see some output from processing GOES-18 data from
18Feb2024. The first chunk of output shows \"good\" processing when processing
the 1309 UTC imagery. At the bottom, you will see some error output that
occurred when processing the 1310 UTC imagery.

Fortunately, the vast majority of the time cspp-geo-gglm.sh still works
correctly with GOES-18 GLM files, and it always works with GOES-16 GLM files!

Thank you for your help with this one!

Sincerely,

Jim
-----------------------------------------------------------------------------------------------
(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1255) ATTEMPT TO
PROCESS GLM DATA for satellite = GOES-18, sector = full, ccyyddd = 2024049, hhmm
= 1309 UTC at: Sun Feb 18 15:04:31 UTC 2024

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1343)
final_src_directory =
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309*

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1385) 3 GLM LCFA
file(s) will be processed in the upcoming cspp-geo-gglm.sh command.

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1407) (At Sun Feb
18 15:04:31 UTC 2024 Execute:
/home/shared/bin/cspp-geo-gridded-glm-1.0/bin/cspp-geo-gglm.sh --goes-sector
full
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309000_e20240491309200_c20240491309210.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309200_e20240491309400_c20240491309414.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491309400_e20240491310000_c20240491310010.nc

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1542) (At Sun Feb
18 15:04:54 UTC 2024 Execute: mkdir -pv
/reimaginator/data/apollo/awg_imagery/glm/LCFA/goes18/2024/2024049/full

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1562) (At Sun Feb
18 15:04:54 UTC 2024 Execute: cp -pv CG_GLM-L2-GLMF-_G18_s20240491309.nc
/reimaginator/data/apollo/awg_imagery/glm/LCFA/goes18/2024/2024049/full/.

\'CG_GLM-L2-GLMF-M3_G18_s20240491309000_e20240491310000_c20240491504320.nc\'
-&gt;
\'/reimaginator/data/apollo/awg_imagery/glm/LCFA/goes18/2024/2024049/full/./CG_GLM-L2-GLMF-M3_G18_s20240491309000_e20240491310000_c20240491504320.nc\'

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1589) (At Sun Feb
18 15:04:54 UTC 2024 Execute: rm -fv CG_GLM-L2-GLMF-_G18_s20240491309.nc

removed
\'CG_GLM-L2-GLMF-M3_G18_s20240491309000_e20240491310000_c20240491504320.nc\'

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1255) ATTEMPT TO
PROCESS GLM DATA for satellite = GOES-18, sector = full, ccyyddd = 2024049, hhmm
= 1310 UTC at: Sun Feb 18 15:04:54 UTC 2024

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1343)
final_src_directory =
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310*

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1385) 3 GLM LCFA
file(s) will be processed in the upcoming cspp-geo-gglm.sh command.

(build_goes_abi_2km_grids_of_glm_data3.scr) (See script line # 1407) (At Sun Feb
18 15:04:54 UTC 2024 Execute:
/home/shared/bin/cspp-geo-gridded-glm-1.0/bin/cspp-geo-gglm.sh --goes-sector
full
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310000_e20240491310200_c20240491310207.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310200_e20240491310400_c20240491310408.nc
/arcdata/goes_restricted/grb/goes18/2024/2024_02_18_049/glm/L2/LCFA/OR_GLM-L2-LCFA_G18_s20240491310400_e20240491311000_c20240491311008.nc

ERROR:main:\'NoneType\' object has no attribute \'groups\'
ERROR:main:Gridding minute 2024-02-18 13:10:00 failed.

**Comment by djhoese** [comment]
I'm sorry you're still dealing with this and haven't found a resolution. However, unless I'm misreading this, this is not a Polar2Grid issue so it should not be filed in the Polar2Grid repository as it is right now.

Additionally, while I'm surprised things weren't resolved with the CSPP Geo group mailing list, Nick Bearson was the lead on the project and left SSEC for a new opportunity shortly after his last response to the thread (if I'm remembering things correctly). It took time after this to get others introduced to the project and it is possible your issue got lost in this transition.

Could you please bring this issue up again with the cspp geo list instead of the Polar2Grid repository? I should be on the email list that will receive your message and will try my best to get the necessary people to look at it.

**Comment by jpnIII** [comment]
Thank you very much, Dave – Will do!

Hope you have a fine weekend!

Sincerely,

Jim
