### ISSUE TITLE
Are there any plans to add more GOES ABI L2 products to the Geo2Grid queue of products?

### ISSUE THREAD

**Issue by jpnIII** [ssec/polar2grid#721]
Greetings, all -- Are there any plans to add any more GOES ABI L2 products to the current queue of Geo2Grid L2 products:

      'AOD', 'HT', 'LST', 'TEMP', 'Fog_Depth', 'IFR_Fog_Prob', 'LIFR_Fog_Prob', 'MVFR_Fog_Prob'

1.)  For our (JPN, Tim, Mat) $0.02-worth, we would vote for adding both CMIP and MCMIP (multi-band) L2 products.   
2.)  As you know, there are a ton of GOES ABI L2 products.   You may have already considered this -- but would some type of generic reader be a reasonable approach to handle the remaining L2 products?  I would think that all of the L2 products list min/max values within the file.  Some type of generic linear colorscale might then a general enhancement?   I know -- words are cheap... 

Thank you for your considerations!

Sincerely,

Jim

**Comment by djhoese** [comment]
The CMIP and MCMIP files and all other L2 files should be supported already but are not an advertised feature. They fall under the "satpy supports it, but Geo2Grid doesn't" umbrella. So if you specify those types of files for the abi_l2_nc reader and say `--list-products-all` you should see the names of the datasets/variables you can load from the files. Again, no guarantees but I would still be interested in how it goes for you.

**Comment by jpnIII** [comment]
Ahh – I’ll take a look.    Thank you, Dave!

Sincerely,

Jim

**Comment by jpnIII** [comment]
Hi Dave et al. – I have had some luck using abi_l2_reader and specifying the correct input L2 file pathname.

Please see:   https://cimss.ssec.wisc.edu/goes/rt/jimn/geo2grid/

Later.

Jim

From: James P. Nelson ***@***.***>
Sent: Monday, November 11, 2024 4:10 PM
To: ssec/polar2grid ***@***.***>; ssec/polar2grid ***@***.***>
Cc: James P. Nelson ***@***.***>; Tim J Schmit - NOAA Federal ***@***.***>; Mat Gunshor ***@***.***>
Subject: RE: [ssec/polar2grid] Are there any plans to add more GOES ABI L2 products to the Geo2Grid queue of products? (Issue #721)

Ahh – I’ll take a look.    Thank you, Dave!

Sincerely,

Jim

**Comment by jpnIII** [comment]
Wow – Really impressive!

I have been able to generate C02 and C13 loops from L1b, L2 CMIPC and L2 MCMIPC input NetCDF files via Geo2Grid (see the loops at https://cimss.ssec.wisc.edu/goes/rt/jimn/geo2grid/).

Programmatically, I assume that you must be internally (within Geo2Grid)  “linking up” for example C02 (that is the Geo2Grid variable I am specifying on the geo2grid.sh commandline) to the following NetCDF variables:  Rad (L1b sector=RadC),  CMI (L2 sector=CMIPC) and CMI_C02 (L2 sector=MCMIPC).   And then I was able to use the same colortable for all three of the TIF output images.   Very nice.  ☺

Thank you!

Sincerely,

Jim

From: James P. Nelson
Sent: Monday, November 11, 2024 6:28 PM
To: ssec/polar2grid ***@***.***>; ssec/polar2grid ***@***.***>
Cc: Tim J Schmit - NOAA Federal ***@***.***>; Mat Gunshor ***@***.***>; James P. Nelson ***@***.***>
Subject: RE: [ssec/polar2grid] Are there any plans to add more GOES ABI L2 products to the Geo2Grid queue of products? (Issue #721)

Hi Dave et al. – I have had some luck using abi_l2_reader and specifying the correct input L2 file pathname.


Please see:   https://cimss.ssec.wisc.edu/goes/rt/jimn/geo2grid/

Later.

Jim

From: James P. Nelson ***@***.******@***.***>>
Sent: Monday, November 11, 2024 4:10 PM
To: ssec/polar2grid ***@***.******@***.***>>; ssec/polar2grid ***@***.******@***.***>>
Cc: James P. Nelson ***@***.******@***.***>>; Tim J Schmit - NOAA Federal ***@***.******@***.***>>; Mat Gunshor ***@***.******@***.***>>
Subject: RE: [ssec/polar2grid] Are there any plans to add more GOES ABI L2 products to the Geo2Grid queue of products? (Issue #721)

Ahh – I’ll take a look.    Thank you, Dave!

Sincerely,

Jim

**Comment by djhoese** [comment]
Glad it worked!
