### ISSUE TITLE
Imagery EDR geoTIFs

### ISSUE THREAD

**Issue by wstraka3** [ssec/polar2grid#74]
FEATURE REQUEST:

Once the EDRs are integrated into CSPP, it would be good to have p2g be able to create two flavors of Imagery EDR geoTIFs

1). "Standard" scaled geoTIFs (i.e. square root enhanced vis and NCC albedos, BT scaled BTs)

2). Raw value geoTIFs of NCC albedos (would allow users to do physical comparisons of NCC product between images). This may need to have the albedos x100, depending on the range of the NCC product.

**Comment by dasantek** [comment]
It's been several years since this ticket was open; does polar2grid work with NCC files? I don't see mention in the documentation.

**Comment by djhoese** [comment]
@dasantek No they are not supported, sorry. The first step in supporting them would be to get a reader in Satpy, but since we don't have funding for this and there hasn't been a demand for it, it likely won't be done by the P2G team directly.
