### ISSUE TITLE
4 km MODIS products interpolate through missing data

### ISSUE THREAD

**Issue by kathys** [ssec/polar2grid#88]
Just started running the 4km polar2grid MODIS products in the Hawaii domain and noticed that the software interpolates through missing data, which we do not want it to do.   The attached images show an image of the water vapor band 27 data, the TPW product image created using McIDAS-X, and a screen capture of the TPW product as displayed in AWIPS.

![screen shot 2013-09-05 at 4 27 28 pm](https://f.cloud.github.com/assets/1848019/1092001/9c402cb6-1672-11e3-910d-613f424db10a.png)
![screen shot 2013-09-05 at 4 27 12 pm](https://f.cloud.github.com/assets/1848019/1092003/a3cb66b2-1672-11e3-98da-1a20953950d0.png)
![screen shot 2013-09-05 at 4 27 40 pm](https://f.cloud.github.com/assets/1848019/1092004/a7345390-1672-11e3-927a-1aae7a28428b.png)

I put the data set that I was using  here: ftp://ftp.ssec.wisc.edu/pub/incoming/HAWAII_MODIS_DATA.tar.gz

**Comment by davidh-ssec** [comment]
@kathys, do you know if this is still a problem?

**Comment by kathys** [comment]
Yes, I think it is still a problem.

Kathy

**Comment by davidh-ssec** [comment]
Do you have a data case that shows this problem that I can get access to?

**Comment by kathys** [comment]
Let me hunt one down.

Kathy

**Comment by davidh-ssec** [comment]
Kathy any chance you have a test case for this old bug report? I'm not sure we ever tackled this problem.

**Comment by kathys** [comment]
I promised to hunt one down, and I see that I did not.  I will put it on my list Dave, and get back to you when I return from AMS meeting.

**Comment by djhoese** [comment]
I'm going to close this as it is extremely old and we now depend on completely different resampling tools that have been rewritten multiple times. I haven't seen this issue since...2013.
